### ISSUE TITLE
value starting with 0 is converted to different number

### ISSUE THREAD

**Issue by vreddhi** [yaml/pyyaml#107]
When using yaml.load(fileContent), where fileContent contains yaml data from a file. If there are any numbers starting with 0, i see that pyYaml is converting it into a different number altogether.

** Example: 
org:
  city: Bangalore
  name: Test Cert
  addressLineTwo:
  addressLineOne: 150 Broadway
  country: US
  region: MA
  phone: 617-555-0111
  postalCode: 02142

In above example postalCode: 02142 is read a postalCode: 1122

**Comment by Zegnat** [comment]
This is not a bug. In YAML 1.1 any integer starting with a `0` is read as an [octal number](https://en.wikipedia.org/wiki/Octal). In this case the parser correctly converts it from an octal to a decimal number, and the decimal version of `02142` is `1122`. (YAML 1.2 changes this and requires `0o`, probably to make this happen less by accident.)

If you need numeral strings starting with a `0`, you should mark them as strings. Either by quoting it:

```yaml
postalCode: "02142"
```

Or by explicitly tagging it:

```yaml
postalCode: !!str 02142
```

**Comment by vreddhi** [comment]
Thank you.
