### ISSUE TITLE
 PyYaml 3-12 version yaml.load() is failing while trying to load example.yaml file

### ISSUE THREAD

**Issue by Bhavana5N** [yaml/pyyaml#109]
PyYaml is providing one example.yaml file in their source package.
**PyYAML-3.12/examples/pygments-lexer/example.yaml**

While loading this yaml file yaml.load() functionality is throwing error as below
_yaml.composer.ComposerError: expected a single document in the stream
  in "PyYAML-3.12/examples/pygments-lexer/example.yaml", line 9, column 1
but found another document
  in "PyYAML-3.12/examples/pygments-lexer/example.yaml", line 14, column 1_

Could it be possible to fix this issue by changing this example.yaml or provide any other solution how to overcome this.

**Comment by perlpunk** [comment]
This document has to be loaded with `load_all` instead of `load` because it contains several documents.
However, this will also fail because it contains structures that cannot (currently) be represented with PyYAML (it contains a list as a dict key).
The example is meant only for the lexer.
