### ISSUE TITLE
Parser fails when custom tagging an alias reference

### ISSUE THREAD

**Issue by shakedel** [yaml/pyyaml#114]
Parser fails on following example (considered valid by all YAML linters I tried)

```
    import yaml

    yml = """
        key1: &REF some_value
        key2: !echo *REF
    """

    def echo(loader, node):
        print(node)
        return node

    yaml.add_constructor('!echo', echo)
    yaml.load(yml)
```

**Comment by perlpunk** [comment]
Which YAML linter did you try? This is invalid in libyaml, js-yaml, snakeyaml, yaml-cpp, ruby psych, ruamel, nimyaml.
An alias cannot have a tag or a key. The referenced node itself can have a tag, so an alias with a tag would have two tags.

**Comment by shakedel** [comment]
After inspecting the YAML documentation the example above is indeed invalid.
There is an ugly workaround though:
```
import yaml

yml = """
    key1: &REF some_value
    key2: !ref [*REF]
"""

def refscalar(loader, node):
    seq = loader.construct_sequence(node)
    return seq[0]

yaml.add_constructor('!ref', refscalar)
print(yaml.load(yml))
```
By the way, here are a couple of online validators that agree with the invalid example: https://codebeautify.org/yaml-validator, https://jsonformatter.org/yaml-validator.
I will stay away from them in the future.
