### ISSUE TITLE
Parser fails when aliasing an alias reference

### ISSUE THREAD

**Issue by shakedel** [yaml/pyyaml#115]
The following code fails
```
import yaml

yml = """
    key1: &REF1 val1
    key2: &REF2 *REF1
"""

yaml.load(yml)

```

**Comment by perlpunk** [comment]
An alias cannot have an anchor. This is also invalid for libyaml, js-yaml, snakeyaml, yaml-cpp, ruby psych, ruamel, nimyaml.

**Comment by shakedel** [comment]
Right. Sorry for the bother.
