### ISSUE TITLE
Installing yaml for Python 3.6 through pip

### ISSUE THREAD

**Issue by Amir-Arsalan** [yaml/pyyaml#132]
I just noticed that the pip version of yaml only works with python 3.5. I wonder, can someone update the package list on `pypi.python.org` so that people can install yaml for python 3.6 as well?

**Comment by henryborchers** [comment]
I just ran into the same issue!

**Comment by mei-li** [comment]
We also run into it as well. Is it only via pip? @Amir-Arsalan Have you manage to install it via the github repofor python3.6?

**Comment by Amir-Arsalan** [comment]
@mei-li For now I switched back to Python 3.5. Didn't have time to compile the code and wanted to avoid possible headaches.

**Comment by mei-li** [comment]
Problem solved. I was missing `python3.6-dev` package. It got solved with  
`> sudo apt-get install python3.6-dev`

**Comment by Amir-Arsalan** [comment]
It's not about installing Python 3.6. `pip install pyyaml' installs Yaml for up to Python 3.5 only.

**Comment by ingydotnet** [comment]
Can you be more specific on a repro scenario for this?

This is working fine for me:
```
wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz
tar xzf Python-3.6.0.tgz
cd Python-3.6.0
./configure
make
./build/scripts-3.6/pyvenv-3.6 foo
source foo/bin/activate
pip install pyyaml
python -c 'import yaml; print(yaml.load("foo: bar\n"))'
```

**Comment by feluxe** [comment]
`pip install pyyaml` works for me with `Python 3.6`.

    Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
    [GCC 7.2.1 20171224] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import yaml
    >>> f = open('myfile')
    >>> y = yaml.load(f)
    >>> print(y)
    { 'my_item': ...

**Comment by wumpus** [comment]
pip install pyyaml works for me in every release of 3.6.

Given that pyyaml compiles stuff during installation, the most likely problem is that @Amir-Arsalan is missing python development libs in his 3.6 install. Same solution as @mei-li

**Comment by Amir-Arsalan** [comment]
Yes it could be that. I close the issue then.

**Comment by KevinDCruz** [comment]
Virtual Environment Setting 

```
Python version: 3.6.3
Operating system: Windows, 64 Bits
```
 

Keras was not installing because of pyyaml setting not meeting up for python 3.6. I already had Anaconda installed in a different virtualenv with keras working fine (pyyaml module installed). I just used conda install pyyaml instead of pip and it got installed, thereby using `pip install keras` to install the keras library in my new virtual environment.

if you have anaconda installed already, try using

`conda install yaml
`

and see if it works. It worked for me!

**Comment by rishikesh67** [comment]
> `pip install pyyaml` works for me with `Python 3.6`.
> 
> ```
> Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
> [GCC 7.2.1 20171224] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import yaml
> >>> f = open('myfile')
> >>> y = yaml.load(f)
> >>> print(y)
> { 'my_item': ...
> ```

Nice, it worked.
