### ISSUE TITLE
pyyaml.org let's encrypt certificate outdated

### ISSUE THREAD

**Issue by norpol** [yaml/pyyaml#138]
Dear pyyaml-maintainers,

out of convenience I'm using this communication channel to let you know that the let's encrypt certificate is for https://pyyaml.org outdated since yesterday.

Thank you in advance.

**Comment by perlpunk** [comment]
Thanks, as far as I know the pyyaml.org website is not under control of the pyyaml project maintainers. @sigmavirus24 do we know who maintains the site?

**Comment by hugovk** [comment]
The Let's Encrypt certificate is now valid for another month.

![image](https://user-images.githubusercontent.com/1324225/37959891-e195f52e-31bc-11e8-9507-88352effb0e0.png)

**Comment by norpol** [comment]
Indeed! Thank's for fixing.
