### ISSUE TITLE
Reference environment variables in yaml

### ISSUE THREAD

**Issue by MacgradyHuang** [yaml/pyyaml#141]
I've found that many people have the need to reference environment variables in yaml files, which must be a better way to popularize yaml usage. Although I can do this by replace the regex, i think it better for yaml to provides this functionality.

**Comment by perlpunk** [comment]
It should not be something a YAML processor does by default. (It is also not nice regarding security.)
Also, the syntax how to reference the environment variables is missing in your suggestion.

**Comment by ingydotnet** [comment]
@perlpunk is right that this is not a desirable default behavior, but here is a simple solution that might interest you:
```python
import os, yaml

yaml_text = """\
user: !env USER
home: !env HOME
path: !env PATH
"""

yaml.add_constructor('!env', lambda loader, node: os.environ[node.value])

print yaml.load(yaml_text)
```
