### ISSUE TITLE
Add python 3.7 to travis

### ISSUE THREAD

**Issue by perlpunk** [yaml/pyyaml#144]
We should test 3.7, either beta or dev branch
https://docs.travis-ci.com/user/languages/python/

**Comment by hugovk** [comment]
Please see PR #149.

**Comment by tacaswell** [comment]
@DNSGeek the issue is that the tarball on pip has pre-cythonized files which do not properly handle a change to cpython internals.  Installing from the git repository will work.

There should be a setup flag to tell the installer to re-cythonize even if it has the files it needs.

**Comment by hugovk** [comment]
This issue can be closed, Python 3.7 has been added to Travis in #149:

https://github.com/yaml/pyyaml/blob/b6cbfeec35e019734263a8f4e6a3340e94fe0a4f/.travis.yml#L21-L22

**Comment by tacaswell** [comment]
Is there another issue to track that pip install fails on 3.7?

**Comment by hugovk** [comment]
Yes: https://github.com/yaml/pyyaml/issues/126.
