### ISSUE TITLE
Update GitHub summary as it points to legacy site

### ISSUE THREAD

**Issue by gene1wood** [yaml/pyyaml#148]
Currently the summary test for this GitHub repo is "`Canonical source repository for PyYAML http://pyyaml.org/`"

![image](https://user-images.githubusercontent.com/1134034/37795066-9a98a6b6-2dd0-11e8-8928-d8d5ca5b669b.png)

When you go to that link though it says

"`PyYAML and LibYAML are now maintained at https://github.com/yaml. This page is left for historical purposes.`"

It probably makes sense to update the GitHub summary and remove reference to this deprecated(?) site.

**Comment by ingydotnet** [comment]
Actually the Description field is 'Canonical source repository for PyYAML' and the Website field is http://pyyaml.org/. ie 2 fields that get displayed next to each other.

I just removed the Website and I will soon update the readme to be modern and correct.

Cheers.

**Comment by hugovk** [comment]
By the way, it's now possible for Markdown READMEs to be shown on PyPI:

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
