### ISSUE TITLE
Add type hints to public interfaces

### ISSUE THREAD

**Issue by gaul** [yaml/pyyaml#153]
This will avoid warnings in with mypy in user software.

**Comment by gaul** [comment]
Sorry I realized that typeshed will address my issue.

**Comment by ssbarnea** [comment]
Maybe the decision to outsource the type hints can be reconsidered in 2021 and we can finally adopt them directly into pyyaml.

I ended up having to propose https://github.com/python/typeshed/pull/5144 just to get a little bit more type support but we can easily see that use of typeshed does not scale well.

**Comment by staticdev** [comment]
@gaul @yaml current version of mypy (June 2021) complains about pyyaml explicitly asking us, as a hint to install a separate types-PyYAML package.

PLEASE consider incorporating this to this package all projects that use it together with mypy don't need an additional package. Maybe reopen this issue?
