### ISSUE TITLE
Any plans to release a new version?

### ISSUE THREAD

**Issue by benkuhn** [yaml/pyyaml#154]
I would love to be able to install a version of pyyaml with #74 merged, but it looks like the PyPI package for pyyaml [hasn't been updated](https://pypi.python.org/pypi/PyYAML) since August 2016. Are there any plans to release a new package version? Or am I looking in the wrong place?

**Comment by ingydotnet** [comment]
Yes. There are plans to do a new release in the upcoming weeks.

**Comment by dmitry-vakhnenko** [comment]
Any updates?

**Comment by rasmusagren** [comment]
And I would be very happy for a new release with PR #143 merged!

**Comment by penguinolog** [comment]
#161 and #163 also useful for new release

**Comment by balloob** [comment]
@ingydotnet is there anything we can do to help with the release? Python 3.7 is around the corner and it is not compatible with the latest published release, but is compatible with master.

**Comment by askoretskiy** [comment]
If it makes difference, maybe first release PyYAML 3.13 with current state of the master branch (it already resolves many issues, like Python 3.7 support) and include new PRs in next releases.

**Comment by danpalmer** [comment]
@ingydotnet hey any plans to release? We're looking to use some of the bug fixes from this time last year and were quite surprised to see they hadn't been released.

**Comment by ingydotnet** [comment]
When is the Python 3.7 release planned to happen?

I have a another conference next week that I'm week that I'm preparing for, but I think with the right people we can triage this.

One thing to consider is that pyyaml is built on libyaml so we need to time the releases in parallel. @alex has already addessed the wheels building for that.

Here's an idea, why don't a bunch of us gather on #pyyaml on irc.freenode.net and we can mob this. pyyaml is an important package and I want to get it right.

I'm currently in UTC-6 timezone and online most of the time from 9am - midnight. See you in #pyyaml.

Specifically calling out @sigmavirus24 @alex @perlpunk but the more the merrier...

**Comment by hugovk** [comment]
Python 3.7 is due out on 2018-06-27. 

Release candidate 1 is already out. 

https://www.python.org/dev/peps/pep-0537/#release-schedule

**Comment by FRidh** [comment]
pyyaml 4.01?
https://github.com/yaml/pyyaml/commit/4c2e993321ad29a02a61c4818f3cef9229219003

**Comment by hugovk** [comment]
> **4.01 Release**
> 
> It's time to put out a new release of PyYAML.
> 
> No release has happened since Kirill turned over the process in Aug 2016. The current PyYAML is incompatible with the new Python 3.7 release this week.
> 
> This release will be version 4.01. A lot of pull requests have been applied since the last release, including fixes for Python 3.7 problems.
> 
> The goal is to get this released by Tuesday, June 26th, 2018.

https://github.com/yaml/pyyaml/projects/1

**Comment by precise-dilution** [comment]
Would love to see https://github.com/yaml/pyyaml/issues/139 addressed

**Comment by The-Compiler** [comment]
Looks like it's been released in the meantime! :tada: Thanks a lot for everyone involved!

**Comment by KevinHock** [comment]
Oh wow I know you @The-Compiler :)
