### ISSUE TITLE
C-type quiet NaN not parsed as float by yaml load

### ISSUE THREAD

**Issue by timsyapel** [yaml/pyyaml#167]
C++ applications write quiet NaN to YAML as "-1.#QNAN".  
Reading this in Python results in a string instead of a float.

**Comment by perlpunk** [comment]
The string `-1.#QNAN` is not special in YAML. Not in YAML 1.1, not in YAML 1.2.
It should be loaded as a string.
Look here for the schema definitions: https://perlpunk.github.io/yaml-test-schema/schemas.html

If you want a NaN, you need to write `.nan`. Also C++ applications must write `.nan`.

Alternatively, create your own custom resolver and constructor.
