### ISSUE TITLE
Confusing repository

### ISSUE THREAD

**Issue by asomov** [yaml/pyyaml#18]
Should this repository clearly indicate that it is not the master repo for PyYAML ?
It may lead to misunderstanding if developers contribute here instead of the master:
https://bitbucket.org/xi/pyyaml

**Comment by JonathonReinhart** [comment]
At the top of the [project home page](https://github.com/yaml/pyyaml), it very clearly (although redundantly) states:

> Mirror of http://svn.pyyaml.org/pyyaml/ http://svn.pyyaml.org/pyyaml/

**Comment by basicdays** [comment]
Is this still true? The top of the project home page now states "Canonical source repository for PyYAML". To make this even more confusing, there's issues here, on the old Trac page, and over at BitBucket. On top of that, there's the old SVN code at the Trac site, git repo at BitBucket, and a git repo here. I'm not even sure where I could contribute...

**Comment by asomov** [comment]
1. Find the link - Canonical source repository for PyYAML **http://pyyaml.org/**
2. When you open http://pyyaml.org/ you see only one link - Moving to BitBucket. Please leave your bug reports there: PyYAML =>  http://bitbucket.org/xi/pyyaml;
3. Unfortunately no one wants to remove confusing "Canonical source repository for PyYAML" from the Github page. Which leads to the question - is this repository maintained ?

**Comment by ixti** [comment]
If I recall correctly this repo should be considered as canonical.
@ingydotnet correct me if i'm wrong.

**Comment by sigmavirus24** [comment]
> is this repository maintained ?

It is and it is the canonical source. We just don't have the time to be actively developing it. I'm trying to get more time for that exact purpose.

**Comment by basicdays** [comment]
If you are open to it, I wouldn't mind pitching in a bit to update the readme on this repo to reflect this information. I'd also be open to porting over the documentation into either an rst or md file to be stored in this repo as well. I've mostly written in markdown syntax, but I know a lot of pythoners like restructured text.

http://pyyaml.org/wiki/PyYAMLDocumentation

**Comment by sigmavirus24** [comment]
@basicdays I'd merge a pull request that updates the README to include that information.

Let's take it one at a time though, e.g., add information to the README in one pull request, convert to reStructuredText in another.

**Comment by basicdays** [comment]
Roger that, happy to help. Will split this into two tickets for what it's worth.
