### ISSUE TITLE
4.1 release breaks old config files

### ISSUE THREAD

**Issue by mjpost** [yaml/pyyaml#180]
[Our project](https://github.com/awslabs/sockeye) uses pyyaml to load configuration files, and our Travis CI builds started breaking recently due to the 4.1 upgrade. One problem is that pyyaml seems no longer to respect types. For example, the following config file:

```
buckets:
- !!python/tuple
  - 9
  - 10
- !!python/tuple
  - 18
  - 20
```

used to get instantiated as a dictionary containing a list of tuples of integer pairs under the key `buckets`, but these tuples are now lists. Creating the same object as a Python dictionary (with a list of tuples of integer pairs) is also written out into a plain file now, such that the type information is lost.

Is there a workaround? Or more generally, a pyyaml 3 → 4 upgrade guide, or list of potential problems?

**Comment by alex** [comment]
See #177 for more details.
