### ISSUE TITLE
ext/_yaml.c is missing in 4.1 tarball

### ISSUE THREAD

**Issue by dfroger** [yaml/pyyaml#182]
Installing `pyyaml 3.12` without `cython` do build the `_yaml` extension, but installing `4.1` do not:

```
python -m venv venv3.12
./venv3.12/bin/pip install pyyaml==3.12

python -m venv venv4.1
./venv4.1/bin/pip install pyyaml==4.1

find . -name '_yaml*'
./venv3.12/lib/python3.6/site-packages/_yaml.cpython-36m-x86_64-linux-gnu.so
```

The problem is that in https://pypi.org/simple/pyyaml/ `PyYAML-3.12.tar.gz` contains `ext/_yaml.c`, but `PyYAML-4.1.tar.gz` do not, so `cython` is required for `4.1` to build the extension. (`.pyx` -> `.c`)

(question also asked in #179 but the issue was about another problem and is closed)

Could it be possible to make a new `4.1` tarball including `ext/_yaml.c`?

**Comment by ingydotnet** [comment]
Will address soon. https://github.com/yaml/pyyaml/issues/179#issuecomment-400909325

**Comment by asottile** [comment]
@ingydotnet the usual way to fix this is to ensure `cython` is installed when uploading the release sdist -- a simple version bump and re-upload would fix this issue (and an assertion in setup.py that `cython` is _required_ during `sdist` would prevent it in the future)

**Comment by asottile** [comment]
for instance, here's what [shapely does](https://github.com/Toblerity/Shapely/blob/4433a841d379044bdca0a891f8fe79c6eed4e06d/setup.py#L317-L329)

**Comment by perlpunk** [comment]
@asottile I created #188, thanks
unfortunately, now travis-ci complains: https://travis-ci.org/yaml/pyyaml/builds/397951551 because of missing cython

**Comment by asottile** [comment]
@perlpunk I sent a PR to your branch: https://github.com/perlpunk/pyyaml/pull/1
