### ISSUE TITLE
!!python/object/apply: does not work anymore since v4

### ISSUE THREAD

**Issue by Colin-b** [yaml/pyyaml#183]
Hi,

It seems there is a regression between version 3.12 and 4.1 (or am I missing something that changed between both versions as this is a major release?)

pip install pyyaml==3.12

`
import yaml

yaml.load("!!python/object/apply:os.getenv ['COMPUTERNAME', None]")
`
Works fine

pip install pyyaml==4.1

`
import yaml

yaml.load("!!python/object/apply:os.getenv ['COMPUTERNAME', None]")
`

Traceback (most recent call last):
...
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:os.getenv'
  in "<unicode string>", line 1, column 1:
    !!python/object/apply:os.getenv  ... 
    ^

**Comment by alex** [comment]
See #177
