### ISSUE TITLE
PyYAML 4.1 changes "safe" in more ways than immediately obvious

### ISSUE THREAD

**Issue by cdent** [yaml/pyyaml#187]
It's clear from the changelog that pyyaml 4.x now defaults to a style of safe_load for loading. This is probably good. However, it also appears that the definition of "safe" has changed somewhat.

In https://github.com/cdent/gabbi/pull/252 the 'safe' related tests work differently depending on whether >4 or <4 is used. As currently written they pass with 4 and fail with 3. The difference seems to be that "safe" in 3 and 4 mean different things:

* in 4, safe will load custom tags that are defined in the same process, but not `python/object`, and unsafe will not load custom tags, but will load `python/object`
* in 3, custom tags only load in unsafe, and `python/object`, neither in safe

The branch on that pull request can demonstrate the problem with different PyYAML versions. And master in the same repo will as well.

**However**, I have no confidence that I'm parsing what's going on properly at all, so I need to come up with a minimal test case, which I'll try to do real soon, but I first wanted to get this written down in case there is something obviously wrong in either my code or in PyYAML.

I will followup to this with the MTC, ASAP. Sorry for dropping noise like this, but needed to dump state.

**Comment by cdent** [comment]
Here's a gist which demonstrates the different behaviors: https://gist.github.com/cdent/130181f02f7cb2737f81fef2ebffc8d3

**Comment by perlpunk** [comment]
I wrote up an example of the different behaviour of `safe_load` and `SafeLoader`.

```
# examples/safe.py
import yaml
import os

# we add a constructor that is potentially dangerous
def myconstructor(loader, node):
    value = loader.construct_scalar(node)
    os.system("echo hello " + value)
    return value

yaml.add_constructor(u'!hello', myconstructor)

string = "msg: !hello world"

print("============ Loading trusted YAML")

data = yaml.load(string)
print(data)

# somewhere else in your application
unsafe_yaml = "msg: !hello evil"

print("============ Loading untrusted YAML")
try:
    safe_data = yaml.safe_load(unsafe_yaml)
    print(safe_data)
except yaml.constructor.ConstructorError as err:
    print("Could not load unsafe_yaml:")
    print(format(err))
```

```

% git co d856c20 # before #74
% python examples/safe.py
hello world
============ Loading trusted YAML
{'msg': u'world'}
============ Loading untrusted YAML
Could not load unsafe_yaml:
could not determine a constructor for the tag '!hello'
  in "<string>", line 1, column 6:
    msg: !hello evil
         ^

% git checkout master
% python examples/safe.py
hello world
hello evil
============ Loading trusted YAML
{'msg': u'world'}
============ Loading untrusted YAML
{'msg': u'evil'}

```

**Comment by ingydotnet** [comment]
PyYAML 5.1 is released now. https://pypi.org/project/PyYAML/5.1/

See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation for safety details.
