### ISSUE TITLE
4.1 release unpublished from PyPI?

### ISSUE THREAD

**Issue by alexbecker** [yaml/pyyaml#190]
We use `pipenv` to manage dependencies, so for our deployed environments we are pinned to specific versions of packages. Earlier today we updated our dependencies, pulling in `pyyaml` version `4.1`. Later our builds started failing, and I could not longer find version `4.1` on https://pypi.org/project/PyYAML/#history. Was it intentionally unpublished?

**Comment by ingydotnet** [comment]
Yes, the 4.1 release had problems from the moment we released it and we were unable to resolve them within 48 hours so we made the decision to retract it. We are working on the 4.2 release now and want to get it out ASAP.

I'm sorry for the inconvenience.
