### ISSUE TITLE
removal of 4.1 broke downstream gates

### ISSUE THREAD

**Issue by prometheanfire** [yaml/pyyaml#192]
http://logs.openstack.org/91/578291/2/check/requirements-tox-py27-check-uc/d6c84fe/job-output.txt.gz#_2018-06-29_05_13_33_345222

**Comment by prometheanfire** [comment]
https://doughellmann.com/blog/2016/02/25/so-youve-released-a-broken-package-to-pypi-what-do-you-do-now/

**Comment by penguinolog** [comment]
Removal of the package (and distribution files) is a really bad thing. As result, all instances with frozen requirements immediately became broken.

**Comment by edmorley** [comment]
Same for us:
https://travis-ci.org/mozilla/treeherder/jobs/398044815#L583

**Comment by orsinium** [comment]
It's broke our locked production requirements too.

**Comment by adamcharnock** [comment]
Having the same problem here.

**Comment by ingydotnet** [comment]
I apologize for the fallout on this decision. We were between a rock and a hard place, and we decided that removing a badly broken 4.1 would cause more trouble the longer we waited.

See https://github.com/yaml/pyyaml/issues/193 for details and the path forward to 4.2.
