### ISSUE TITLE
Collections Deprecation Warning

### ISSUE THREAD

**Issue by jeoffridavis** [yaml/pyyaml#202]
**Warning**
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Offending Code**
In constructor.py , line 126:
`  if not isinstance(key, collections.Hashable):`

**Comment by tirkarthi** [comment]
Relevant PR : https://github.com/yaml/pyyaml/pull/212/files

Thanks

**Comment by jfthuong** [comment]
> Relevant PR : #212
> 
> Thanks

And alos #181 ... I guess everyone coming to this issue wants to report it. It's good ;)

**Comment by et304383** [comment]
Why isn't this fixed yet?

**Comment by perlpunk** [comment]
Fixed by #181
