### ISSUE TITLE
Version 3.13 fails test suite after libyaml update to 0.2.1

### ISSUE THREAD

**Issue by peti** [yaml/pyyaml#214]
Hi,

we're trying to upgrade our `libyaml` in NixOS to version 0.2.1 (https://github.com/NixOS/nixpkgs/pull/45560), but we're having trouble because [that update breaks the test suite of `pyyaml`](https://github.com/NixOS/nixpkgs/pull/45560#issuecomment-416151111), which feels like that's not something that's supposed to happen. The complete build log is visible at https://logs.nix.ci/?key=nixos/nixpkgs.45560&attempt_id=1ccf9c4d-e201-4f4c-a9f5-d84a1ede48be, and the relevant bits are:

    running install tests
    running test
    running build_py
    running build_ext
    ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................FF..F.....F....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    ===========================================================================
    test_emitter_styles_ext(tests/data/spec-07-09.data, tests/data/spec-07-09.canonical): FAILURE
    Traceback (most recent call last):
      File "tests/lib/test_appliance.py", line 65, in execute
	function(verbose=verbose, *filenames)
      File "tests/lib/test_yaml_ext.py", line 240, in wrapper
	function(*args, **kwds)
      File "tests/lib/test_emitter.py", line 62, in test_emitter_styles
	_compare_events(events, new_events)
      File "tests/lib/test_emitter.py", line 15, in _compare_events
	assert event1.value == event2.value, (event1, event2)
    AssertionError: see below
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    (ScalarEvent(anchor=None, tag=u'tag:yaml.org,2002:str', implicit=(False, False), value=u'foo'),
     ScalarEvent(anchor=None, tag=u'tag:yaml.org,2002:str', implicit=(False, False), value=u'foo %YAML 1.1'))
    ---------------------------------------------------------------------------
    tests/data/spec-07-09.data:
    ---
    foo
    ...
    # Repeated end marker.
    ...
    ---
    bar
    # No end marker.
    ---
    baz
    ...
    ---------------------------------------------------------------------------
    tests/data/spec-07-09.canonical:
    %YAML 1.1
    ---
    !!str "foo"
    %YAML 1.1
    ---
    !!str "bar"
    %YAML 1.1
    ---
    !!str "baz"
    ===========================================================================
    test_emitter_styles_ext(tests/data/spec-07-10.data, tests/data/spec-07-10.canonical): FAILURE
    Traceback (most recent call last):
      File "tests/lib/test_appliance.py", line 65, in execute
	function(verbose=verbose, *filenames)
      File "tests/lib/test_yaml_ext.py", line 240, in wrapper
	function(*args, **kwds)
      File "tests/lib/test_emitter.py", line 62, in test_emitter_styles
	_compare_events(events, new_events)
      File "tests/lib/test_emitter.py", line 15, in _compare_events
	assert event1.value == event2.value, (event1, event2)
    AssertionError: see below
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    (ScalarEvent(anchor=None, tag=u'tag:yaml.org,2002:str', implicit=(False, False), value=u'Root flow scalar'),
     ScalarEvent(anchor=None, tag=u'tag:yaml.org,2002:str', implicit=(False, False), value=u'Root flow scalar %YAML 1.1'))
    ---------------------------------------------------------------------------
    tests/data/spec-07-10.data:
    "Root flow
     scalar"
    --- !!str >
     Root block
     scalar
    ---
    # Root collection:
    foo : bar
    ... # Is optional.
    ---
    # Explicit document may be empty.
    ---------------------------------------------------------------------------
    tests/data/spec-07-10.canonical:
    %YAML 1.1
    ---
    !!str "Root flow scalar"
    %YAML 1.1
    ---
    !!str "Root block scalar\n"
    %YAML 1.1
    ---
    !!map {
      ? !!str "foo"
      : !!str "bar"
    }
    ---
    #!!str ""
    !!null ""
    ===========================================================================
    test_emitter_styles_ext(tests/data/spec-07-13.data, tests/data/spec-07-13.canonical): FAILURE
    Traceback (most recent call last):
      File "tests/lib/test_appliance.py", line 65, in execute
	function(verbose=verbose, *filenames)
      File "tests/lib/test_yaml_ext.py", line 240, in wrapper
	function(*args, **kwds)
      File "tests/lib/test_emitter.py", line 62, in test_emitter_styles
	_compare_events(events, new_events)
      File "tests/lib/test_emitter.py", line 15, in _compare_events
	assert event1.value == event2.value, (event1, event2)
    AssertionError: see below
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    (ScalarEvent(anchor=None, tag=u'!foo', implicit=(False, False), value=u'No directives'),
     ScalarEvent(anchor=None, tag=u'!foo', implicit=(False, False), value=u'No directives %TAG ! %21foo'))
    ---------------------------------------------------------------------------
    tests/data/spec-07-13.data:
    ! "First document"
    ---
    !foo "No directives"
    %TAG ! !foo
    ---
    !bar "With directives"
    %YAML 1.1
    ---
    !baz "Reset settings"
    ---------------------------------------------------------------------------
    tests/data/spec-07-13.canonical:
    %YAML 1.1
    ---
    !!str "First document"
    ---
    !<!foo> "No directives"
    ---
    !<!foobar> "With directives"
    ---
    !<!baz> "Reset settings"
    ===========================================================================
    test_emitter_styles_ext(tests/data/spec-08-08.data, tests/data/spec-08-08.canonical): FAILURE
    Traceback (most recent call last):
      File "tests/lib/test_appliance.py", line 65, in execute
	function(verbose=verbose, *filenames)
      File "tests/lib/test_yaml_ext.py", line 240, in wrapper
	function(*args, **kwds)
      File "tests/lib/test_emitter.py", line 62, in test_emitter_styles
	_compare_events(events, new_events)
      File "tests/lib/test_emitter.py", line 15, in _compare_events
	assert event1.value == event2.value, (event1, event2)
    AssertionError: see below
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    (ScalarEvent(anchor=None, tag=u'tag:yaml.org,2002:str', implicit=(False, False), value=u'foo bar'),
     ScalarEvent(anchor=None, tag=u'tag:yaml.org,2002:str', implicit=(False, False), value=u'foo bar %YAML 1.1'))
    ---------------------------------------------------------------------------
    tests/data/spec-08-08.data:
    ---
    foo:
     "bar
     baz"
    ---
    "foo
     bar"
    ---
    foo
     bar
    --- |
     foo
    ...
    ---------------------------------------------------------------------------
    tests/data/spec-08-08.canonical:
    %YAML 1.1
    ---
    !!map {
      ? !!str "foo"
      : !!str "bar baz"
    }
    %YAML 1.1
    ---
    !!str "foo bar"
    %YAML 1.1
    ---
    !!str "foo bar"
    %YAML 1.1
    ---
    !!str "foo\n"
    ===========================================================================
    TESTS: 2573
    FAILURES: 4
    error: Tests failed

We are not sure how to proceed. Could you please advice what those errors mean and how we could possibly fix them?

**Comment by perlpunk** [comment]
Yeah, this is a known issue, see also yaml/libyaml#60
The fix (https://github.com/yaml/libyaml/commit/8ee83c0da22fe9aa7dea667be8f899a7e32ffb83, https://github.com/yaml/libyaml/commit/56f4b17221868593d6903ee58d6d679b690cf4df) is in libyaml master, but we haven't created a new release yet...
The bug is unlikely to show up in real world usage, so maybe you can ignore the error for now?

**Comment by peti** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/d6b418cb12b1798801572d7c5e2988ebe3a89dbb.
