### ISSUE TITLE
Link to YAML cookbook is broken

### ISSUE THREAD

**Issue by Muffo** [yaml/pyyaml#215]
The [documentation ](https://pyyaml.org/wiki/PyYAMLDocumentation) includes a link to the YAML cookbook which does not seem to be working: http://yaml4r.sourceforge.net/cookbook/

**Comment by perlpunk** [comment]
thanks!
Luckily it was copied to yaml.org at some point: http://yaml.org/YAML_for_ruby.html

**Comment by perlpunk** [comment]
This was fixed by https://github.com/yaml/pyyaml.org/pull/3
