### ISSUE TITLE
PyYAML and wheel

### ISSUE THREAD

**Issue by 4383** [yaml/pyyaml#227]
According to [this code](https://github.com/yaml/pyyaml/blob/master/setup.py#L91) I suppose that pyyaml can be build without `wheel`.

I suppose we can facing this case when users install pyyaml from source, so, why do not include  requirements that we install before build this package to standardize building process and to simplify setup?

If you agree I can make the necessary changes and propose a pull request to pyyaml.

**Comment by MRigal** [comment]
That would be great! It's also slightly related to #218

**Comment by webknjaz** [comment]
Unfortunately, it's up to @ingydotnet to accept such a contribution. If you want to send a PR, you'll need to build matrixes of (1) manylinux1 wheels, macOS wheels, and Windows wheels.

**Comment by GliderGeek** [comment]
a wheel version would be highly appreciated :+1:

**Comment by nitzmahone** [comment]
addressed in #407 in 5.4b1

**Comment by GliderGeek** [comment]
thanks for fixing this :+1:
