### ISSUE TITLE
Feature Request: Support Nuitka

### ISSUE THREAD

**Issue by Jeeppler** [yaml/pyyaml#229]
[Nuitka](http://nuitka.net/pages/overview.html) is a Python to C cross-compiler. I want to use Nuitka for a command line tool. This command line tool uses PyYaml. However, there is one problem PyYaml uses dynamic import statements. Nuitka does not run the code and therefore is not able to figure out what should be imported, when dynamic imports are used.

Chevron has import fails in PyYAML:

```
$ python3 -m nuitka --follow-imports mycli.py 
Nuitka:WARNING:/usr/local/lib/python3.6/dist-packages/yaml/cyaml.py:5: Cannot find '_yaml' in package 'yaml' as absolute import (tried _yaml).
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/yaml/constructor.py:521' may require use of '--include-plugin-directory' or '--include-plugin-files'.
```

It would be nice if PyYaml could use static imports or find another way supporting Nuitka.

**Comment by ingydotnet** [comment]
@Jeeppler in the upcoming 5.1 release, dynamic importing will only be used by the UnsafeLoader, The new default, FullLoader, does not use dynamic importing. SafeLoader never did.

I *think* that if you commented out the 2 functions in `yaml/constructor.py` that use `__import__` and just use `safe_load`. You would be OK. Try it and let me know.

**Comment by Jeeppler** [comment]
@ingydotnet thanks for the update. The project which I had the problem with, finished. At the end I decided not to use Nuitka, mainly because Nuitka cannot create standalone binaries. Nuitka still needs to have Python installed.
