### ISSUE TITLE
Release_3.13: Dict leading zeros results in 0-7, then "08", "09" ...

### ISSUE THREAD

**Issue by pacman2011** [yaml/pyyaml#231]
Hoping i put this in the correct spot, feel free to move it if I haven't.

**Description:**
In python 2.7.15, using PyYaml 3.13.
When creating a dictionary in the config file, leading zeros are stripped correctly for numbers 0 though 7. However, 8 and 9 are treated as strings.

**Code to Reproduce:**
``` python
import yaml
from pprint import pprint
config_text = """my_dict:
    00: zero
    01: one
    02: two
    03: three
    04: four
    05: five
    06: six
    07: seven
    08: eight
    09: nine
    10: ten
"""
config = yaml.load(config_text)
pprint(config)
```

**Output:**
```
{'my_dict': {0: 'zero',
             1: 'one',
             2: 'two',
             3: 'three',
             4: 'four',
             5: 'five',
             6: 'six',
             7: 'seven',
             10: 'ten',
             '08': 'eight',
             '09': 'nine'}}
```

**Comment by nitzmahone** [comment]
This isn't an implementation bug, it's an artifact of YAML 1.1 behavior around parsing of octal values. The behavior is changed in YAML 1.2 to require a `0o` prefix, but pyyaml is YAML 1.1 only. If you want to preserve the leading zeros today, you'll have to quote the key (eg `"00"`).
