### ISSUE TITLE
[slots] it may be a bug in file constructor.py

### ISSUE THREAD

**Issue by Freakwill** [yaml/pyyaml#232]
If the following code is triggered, then you will be told that there is a TypeError: can't set attributes of built-in/extension type 'object'. I guess it should be setattr(instance, key, value).
```
    def set_python_instance_state(self, instance, state):
        ......
            for key, value in slotstate.items():
                setattr(object, key, value)
```

**Comment by perlpunk** [comment]
Fixed in 5.3: https://pypi.org/project/PyYAML/5.3/
