### ISSUE TITLE
Custom tags fail in block scalars

### ISSUE THREAD

**Issue by christianbioinf** [yaml/pyyaml#238]
I am using custom tags in order to replace environment variables on load which does not seem to work together with block scalars. The toy example code below illustrates this as the custom tag is not detected in presence of block scalars, neither (i) implicitely by the pattern nor (ii) explicitely via using the tag notation (tested with python 3.6.5. and PyYAML 3.13).

```
import re

pattern = re.compile(r'^\$ENV\{([^$]*)\}(.*)$')
yaml.add_implicit_resolver("!envext", pattern)

def construct_envext(loader, node):
    value = loader.construct_scalar(node)
    env_var, remainder = pattern.match(value).groups()
    # for testing purposes:
    return {'temp':'/tmp'}[env_var] + remainder
    # for real applications:
    # return os.environ[env_var] + remainder

yaml.add_constructor('!envext', construct_envext)

data = """
file1: $ENV{temp}/file1
file2: !envext $ENV{temp}/file2
file3: >-
  $ENV{temp}/file3
file4: |-
  !envext $ENV{temp}/file4
"""

print(yaml.load(data))
```

I tried to track down the issue and it seems that for (i) implicit resolvers, only plain scalars are tested and block scalars are set as not plain whereas (ii) the use of explicit tags does not seem to work since due to the missing tag at the beginning (since the first characters are the block scalar indicators) it is not categorized as TagToken but ScalarToken and afterwards there is basically no going back to recognizing the tag.

I was wondering whether it is possible to treat block scalars similarly to other blocks like sequence and mapping and simply parse the inner part (i.e. the multi-line string build according to the block scalar indicators) independently from the outer part (i.e. the block scalar indicators).

**Comment by perlpunk** [comment]
You have a typo for file4:
```
file4: |-
  !envext $ENV{temp}/file4
```
That needs to be:
```
file4: !envext |-
  $ENV{temp}/file4
```
This way the tag is correctly resolved.

**Comment by christianbioinf** [comment]
@perlpunk Thank you very much for your quick and very helpful response. Is there also a simple way to get the `file3` example to be working?

**Comment by perlpunk** [comment]
Sorry for the late reply. Implicit resolvers can only work on plain scalars, not quoted.
