### ISSUE TITLE
Plans to cut stable release?

### ISSUE THREAD

**Issue by kdelee** [yaml/pyyaml#259]
requirements.io has been yelling at this project I've been helping maintain, https://github.com/jlaska/pytest-github because we have `pyYAML` in our requirements file, but this gets 3.13 from pypi because the subsequent releases have been marked as `pre-releases` 

https://pypi.org/project/PyYAML/#history

Do you have plans to cut another stable release?

**Comment by stacybrock** [comment]
There is an active project board for the 5.1 release: https://github.com/yaml/pyyaml/projects/2

I've been keeping an eye on it as I am also very interested in seeing 5.1 released as soon as possible.

**Comment by ssbarnea** [comment]
Can we please have a new RELEASE asap (not pre-release) that covers the CVE issue?

There are lots of projects which have a policy of not listing pre-releases in their requirements.

**Comment by perlpunk** [comment]
We are working on it, but there were several issues that prevented us from doing a final release.

**Comment by alevikpes** [comment]
I got a security alert on github about a vulnerability on the current stable release 3.13. They recommend to update to version >=4.1b1.

I would suggest to make one of the latest releases as `stable`, since some people may not be aware of the security issue and still keep the default one.

**Comment by imnotjames** [comment]
According to https://github.com/yaml/pyyaml/issues/193#issuecomment-468161506 there should be a release in the next few days.

**Comment by ingydotnet** [comment]
We are hoping to have a final release in the next 3 days.

**Comment by ingydotnet** [comment]
FYI...

PyYAML 5.1 appears to be ready to ship in the next 24 hours.

**Comment by ingydotnet** [comment]
PyYAML 5.1 has been released.

https://pypi.org/project/PyYAML/5.1/
