### ISSUE TITLE
convenience methods in __init__.py should modify FullLoader instead of Loader

### ISSUE THREAD

**Issue by dthkao** [yaml/pyyaml#271]
For example `add_constructor()` in 5.1 is a no-op for legacy code since it adds the constructor to Loader but FullLoader is the one used in load(input).

https://github.com/yaml/pyyaml/blob/master/lib3/yaml/__init__.py#L329-L344

**Comment by perlpunk** [comment]
Thanks, we're discussing this. It will always break some code, but since the default for load is FullLoader that seems to be the best.

**Comment by perlpunk** [comment]
I created #274

**Comment by perlpunk** [comment]
This was fixed in 5.2
