### ISSUE TITLE
Print to file exclamation mark

### ISSUE THREAD

**Issue by TebanSierra** [yaml/pyyaml#308]
I'm creating a tempalte from a json object where the value of a key might start with an exclamation mark (!) as follows

```python
data = {
    "Resource": ["arn:aws:logs:*:*:*", "!GetAtt LambdaFunctionName.Arn"]
}
```
When executing:
```python
with open('./template.yaml', 'w') as out_f:
            yaml.safe_dump(data, out_f, default_flow_style=False, sort_keys=False)
```

My `template.yaml` is like this
```yaml
Resource:
- arn:aws:logs:*:*:*
- '!GetAtt LambdaFunctionName.Arn'
```
Even it seems good I can't have the GetAtt line within quote marks. Is there any other argument I can use in either `dump()` or `safe_dump()` to force printing without quotes?

**Comment by perlpunk** [comment]
No, because this would create potentially invalid YAML.
In your case, the resulting YAML would be valid, but semantically different.
If you want to have a tag `!GetAtt` in the output, you have to create an object yourself and add a representer that dumps your object with a tag.

**Comment by perlpunk** [comment]
Closing
