### ISSUE TITLE
Is this time to pass the baton?

### ISSUE THREAD

**Issue by pombredanne** [yaml/pyyaml#31]
This repo is nearing abandonware which is IMHO a sad thing.
I see @sigmavirus24 was trying to get something done a while back.
@dstufft started a sensible fork IMHO here https://github.com/dstufft/yaml
@ingydotnet @xitology what do you think?

**Comment by pombredanne** [comment]
@authbox-lib I see you did some recent work with https://github.com/authbox-lib/pyyaml/commit/ca43af2062d4901cb6ca253677e7b3213bd56131 on top of @dstufft work.

**Comment by pombredanne** [comment]
@xitology I see you started to give this some love recently again at https://bitbucket.org/xi/pyyaml/commits/ ?
which is the master repo?

**Comment by pombredanne** [comment]
But there are also countless pull request there and this https://bitbucket.org/xi/pyyaml/issues/59/has-this-project-been-abandoned

**Comment by kwill** [comment]
To the best of my knowledge (citation needed) this is only a mirror of the bitbucket repo (so maybe issues should be disabled?).

Regarding forks, see also https://bitbucket.org/ruamel/yaml which, amongst other new features, supports YAML 1.2 and content-preserving roundtrips... https://yaml.readthedocs.io/en/latest/overview.html

**Comment by pombredanne** [comment]
@kwill yes, @ruamel fork is excellent and extends the C/Cython of the original pyyaml.
@dtsufft fork has another tack: pure Python only.
and regardless where forks live the "main" forks here or on bitbucket are not what I would call "alive"

**Comment by sigmavirus24** [comment]
@pombredanne yes, we are talking to the author and working out a maintenance plan. @ingy is involved and helping things along. Please be patient.

**Comment by sigmavirus24** [comment]
Good news. I've been given permission to release PyYAML on PyPI and @ingy and I are working on taking over this and libyaml.

We will be doing releases soon.

Consider the baton passed. :)

**Comment by ingydotnet** [comment]
FWIW @ingy is more commonly known as @ingydotnet :)

**Comment by pombredanne** [comment]
@sigmavirus24 @ingydotnet Congrats and thank you!

**Comment by ingydotnet** [comment]
See also:

* yaml/pyyaml#32
* yaml/libyaml#11

**Comment by ingydotnet** [comment]
Reopening until above issues are resolved.

**Comment by pombredanne** [comment]
IMHO the "baton" has been fully passed... And this should be closed.
