### ISSUE TITLE
Using libyaml from pyyaml on Windows

### ISSUE THREAD

**Issue by albertvaka** [yaml/pyyaml#311]
On Windows, the C extension (`_yaml.pyd`) never loads libyaml (`libyaml-0-2.dll`) even if the DLL is installed (eg: in `System32`). 

Is there any way to make pyyaml use the C implementation from libyaml on Windows?

**Comment by nitzmahone** [comment]
If you install one of the Windows wheels from PyPI or the official release downloads, libyaml (currently 0.2.2) is statically linked in. Building a Windows wheel that uses the C library is fraught with peril, and differs a bit for every version of Python, so I'd strongly recommend you use one of the existing wheels. If that doesn't work for you, you're kinda on your own...
