### ISSUE TITLE
Fail to install with pip and python 2.7.10 on OSx 10.14.5

### ISSUE THREAD

**Issue by sedurCode** [yaml/pyyaml#319]
Attempting to install pyyaml on a mac running osx 10.15.5 using latest pip and python 2.7.10.
This package installed correctly using pip3 for python3.
Please see console dump:
`
Installing collected packages: pyyaml, futures, singledispatch, backports-abc, tornado, nose
  Running setup.py install for pyyaml ... error
    ERROR: Complete output from command /usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/gq/x_5hwdvx40vfnmgjk7rd239c0000gn/T/pip-install-zpwUpq/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gq/x_5hwdvx40vfnmgjk7rd239c0000gn/T/pip-record-b4OnNS/install-record.txt --single-version-externally-managed --compile:
    ERROR: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-intel-2.7
    creating build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/scanner.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/error.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/constructor.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/composer.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/events.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/__init__.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/representer.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/tokens.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/dumper.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/cyaml.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/parser.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/reader.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/loader.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/resolver.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/serializer.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/nodes.py -> build/lib.macosx-10.14-intel-2.7/yaml
    copying lib/yaml/emitter.py -> build/lib.macosx-10.14-intel-2.7/yaml
    running build_ext
    building '_yaml' extension
    creating build/temp.macosx-10.14-intel-2.7
    creating build/temp.macosx-10.14-intel-2.7/ext
    cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ext/_yaml.c -o build/temp.macosx-10.14-intel-2.7/ext/_yaml.o
    In file included from ext/_yaml.c:596:
    ext/_yaml.h:2:10: fatal error: 'yaml.h' file not found
    #include <yaml.h>
             ^~~~~~~~
    1 error generated.
    Error compiling module, falling back to pure Python
    running install_lib
    creating /Library/Python/2.7/site-packages/yaml
    error: could not create '/Library/Python/2.7/site-packages/yaml': Permission denied
    ----------------------------------------
ERROR: Command "/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/gq/x_5hwdvx40vfnmgjk7rd239c0000gn/T/pip-install-zpwUpq/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gq/x_5hwdvx40vfnmgjk7rd239c0000gn/T/pip-record-b4OnNS/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/gq/x_5hwdvx40vfnmgjk7rd239c0000gn/T/pip-install-zpwUpq/pyyaml/
`

**Comment by nitzmahone** [comment]
My psychic intuition tells me you're using XCode Python 2.7 and a Python3.x you installed yourself as your current user... XCode Python's `site-packages` path doesn't allow your current user to write there (see the "Permission denied" error to a non-user path), while your Python3.x probably does. You'll need to install with `--user`, a virtualenv, or `sudo` (nothing unique to pyyaml here, this is common practice for any system-owned Python installation).
