### ISSUE TITLE
Syntax errors when running compileall - 5.1.1

### ISSUE THREAD

**Issue by JasonLewis23** [yaml/pyyaml#323]
I'm seeing syntax errors during compilation of pyyaml-5.1.1 (using compileall) in various python2 and python3 versions (more worried about the syntax errors that are not located in the tests/ folder).

Context - In our environment, we package/re-package pypi packages that are needed on Debian distributions if Debian does not contain a more recent version that we require or if Debian is missing the package entirely. This is done using the stdeb pypi package. This package inserts a compileall command (see example below) into the post installation step of the resulting Debian package so that the installation step fails if there are any syntax errors in the package. 

System Info - The attached logs are from a server running Debian Jessie (python 2.7.9 and 3.4.2). Similar syntax errors are also seen on Debian Stretch (python 2.7.13 and 3.5.3) as well as Debian buster (python 3.7.3).

commands to reproduce:
-     pull down tarball
-     tar -xvf  PyYAML-5.1.1.tar.gz
-     cd PyYAML-5.1.1/
-     python -m compileall ./
-     python3 -m compileall ./

[pyyaml_syntaxerrs_debianjessie.txt](https://github.com/yaml/pyyaml/files/3443563/pyyaml_syntaxerrs_debianjessie.txt)

**Comment by nitzmahone** [comment]
If you insist on doing it this way, you'll probably need to filter the lib/ or lib3/ directory from your compliation depending on which Python version you're running on. For historical reasons that haven't yet been corrected, there are currently separate Python2/3 versions of the codebase, so you'll definitely get bogus results trying to use both simultaneously. Regardless, nothing we can do short-term on this end to address that, until the two codebases get re-merged (IIRC there's an open PR for this, but we need to update it and fix a few things before it can be merged).

**Comment by JasonLewis23** [comment]
Thanks for the transparency, I'll pull the source down and modify/track internally until the code bases merge. Ideally we wouldn't have to do this type of building but it's an odd use case and pip isn't an option for us.
