### ISSUE TITLE
does the passed stream need to be closed

### ISSUE THREAD

**Issue by hivemall** [yaml/pyyaml#330]
so simple, yet the doc is silent if i need to close stream 
```
data = yaml.safe_load(open('defaults.yaml'))
```

**Comment by hSaria** [comment]
It does not. You can test that very easily.

```python
>>> file = open('test.yaml')
>>> data = yaml.safe_load(file)
>>> file.closed
False
```

It's best to use `with` to avoid doing that manually or forgetting:
```python
>>> with open('.chromaterm.yml') as file:
...     data = yaml.safe_load(file)
... 
>>> file.closed
True
```

**Comment by nitzmahone** [comment]
This is pretty standard- well-behaved software will not assume it owns the stream to do with as it pleases. Going to close this one here- if someone really wants to add a note to the docs, they're at https://github.com/yaml/pyyaml.org/blob/master/wiki/PyYAMLDocumentation.md
