### ISSUE TITLE
Cut a 5.2 release?

### ISSUE THREAD

**Issue by dthkao** [yaml/pyyaml#336]
The open issues mentioned in #265 appear to be resolved. Is there a plan to actually release 5.2? There haven't been any commits since March.

**Comment by dthkao** [comment]
Friendly ping?

**Comment by dthkao** [comment]
Gentle ping.

**Comment by dthkao** [comment]
Just for context: https://github.com/yaml/pyyaml/projects/3

**Comment by dthkao** [comment]
Respectful ping. 
@ingydotnet @nitzmahone

**Comment by dthkao** [comment]
(bi-)weekly ping.
@perlpunk

**Comment by perlpunk** [comment]
> (bi-)weekly ping.
> @perlpunk

delegating to @ingydotnet PIIIIIING

**Comment by perlpunk** [comment]
I was able to talk to @ingydotnet and I'm trying to prepare a 5.2 release now

**Comment by dthkao** [comment]
woohoo! thank you @perlpunk!

**Comment by perlpunk** [comment]
the release branch is ready. @nitzmahone helps us to create a release in the next days. we'll do a beta release first

**Comment by perlpunk** [comment]
We just uploaded 5.2b1: https://pypi.org/project/PyYAML/5.2b1/
thanks @nitzmahone !

**Comment by perlpunk** [comment]
We released 5.2: https://pypi.org/project/PyYAML/5.2/

**Comment by MRigal** [comment]
@perlpunk you might also close that issue...
