### ISSUE TITLE
Unable to transform OrderedDict data into yaml format

### ISSUE THREAD

**Issue by kcorlidy** [yaml/pyyaml#338]
pyyaml can transform ordinary dict to yaml. But when i transform `OrderedDict` data into yaml format i got unexpected output.
Is there any way can help me complete it successfully? Or i missed some issues?

	import yaml
	from pprint import pprint
	from collections import OrderedDict
	import sys

	doc = """
	Server:
	  - Name: test
	    Domain: test.com
	    Specs:
	      - Hostname: A
	      - Hostname: B
	"""
	data = yaml.load(doc)
	new_data = OrderedDict(
		Server=OrderedDict([('Name','test'),
						('Domain','test.com'),
	            		('Specs',[{'Hostname': 'A'}, {'Hostname': 'B'}])]))
	pprint(data)
	print(yaml.dump(data, default_flow_style=False))

	pprint(new_data)
	print(new_data.get("Server").get("Name") == "test")
	print(yaml.dump(new_data, default_flow_style=False))

	print(yaml.__version__)
	print(sys.version)

Output

	C:\Users\kcorlidy\Desktop\1.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  data = yaml.load(doc)
	{'Server': [{'Domain': 'test.com',
	             'Name': 'test',
	             'Specs': [{'Hostname': 'A'}, {'Hostname': 'B'}]}]}
	Server:
	- Domain: test.com
	  Name: test
	  Specs:
	  - Hostname: A
	  - Hostname: B

	OrderedDict([('Server',
	              OrderedDict([('Name', 'test'),
	                           ('Domain', 'test.com'),
	                           ('Specs',
	                            [{'Hostname': 'A'}, {'Hostname': 'B'}])]))])
	True
	!!python/object/apply:collections.OrderedDict
	- - - Server
	    - !!python/object/apply:collections.OrderedDict
	      - - - Name
	          - test
	        - - Domain
	          - test.com
	        - - Specs
	          - - Hostname: A
	            - Hostname: B

	5.1.2
	3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]

**Comment by kcorlidy** [comment]
I got one way to solve this question. [SO:in-python-how-can-you-load-yaml-mappings-as-ordereddicts](https://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts
). Do pyyaml contain such function?

**Comment by dthkao** [comment]
Are you just looking to dump an OrderedDict the same way as the built-in? Wouldn't this work:

`print(yaml.dump(dict(new_data), default_flow_style=False))`

`

**Comment by kcorlidy** [comment]
> Wouldn't this work:
> 
> `print(yaml.dump(dict(new_data), default_flow_style=False))`

I add your code into my question script. Still going wrong.

        5.1.2
	3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
	Server: !!python/object/apply:collections.OrderedDict
	- - - Name
	    - test
	  - - Domain
	    - test.com
	  - - Specs
	    - - Hostname: A
	      - Hostname: B

@dthkao I think SO answer is a great solution, but i have to add those code each time.

**Comment by dthkao** [comment]
My suggestion only handles the top layer OrderedDict. You'll need the nesting function to properly convert all inner OrderedDicts as well. Use the function so as not to reproduce *too* much code for each dump.

AFAICT pyyaml is doing the expected thing here (for now). This is pretty much the same issue as #315, which boils down to support for more general Mappings (i.e., all oc collections).

Separately, if you're using python 3.6+ then OrderedDict itself shouldn't be necessary (the builtin dict iteration order preserves insertion order).

**Comment by azeemmd** [comment]
This should work `yaml.dump(dictObj,default_flow_style=False,sort_keys=False)`
