### ISSUE TITLE
encoding bug or missue?

### ISSUE THREAD

**Issue by jflorian** [yaml/pyyaml#348]
I have an input file containing:
~~~
78:
    city:           Atlacomulco
    region:         Méx
    country:        Mexico
~~~
And this tidbit of code:
~~~
#!/usr/bin/python3.7

import yaml
with open('input.yaml') as f:
    data = yaml.safe_load(f)
with open('output.yaml', 'w') as f:
    yaml.dump(data, f)
~~~
In the resultant output, I see the _region_ value mutates:
~~~
$ grep region input.yaml | od -c
0000000                   r   e   g   i   o   n   :
0000020                   M 303 251   x  \n
0000031
$ grep region output.yaml | od -c
0000000           r   e   g   i   o   n   :       "   M   \   x   E   9
0000020   x   "  \n
0000023
~~~
This mutation looks like a bug, but I'm a dumb American who stopped paying attention past ASCII so I could easily be doing something wrong here.  If so, help would be greatly appreciated.

**Comment by perlpunk** [comment]
You need to set `allow_unicode`:
```
yaml.dump(data, f, allow_unicode=True)
```

**Comment by jflorian** [comment]
Sure enough, that's exactly the problem!  Thanks for the speedy answer.

**Comment by jflorian** [comment]
Also, I did look at the docs first and found no help.  Initially, I searched for `encod` and `decod` for tips but nothing to guide me here.  Now I search for `allow_unicode` and while there's hits for that, I see nothing that explains its intended use.

**Comment by perlpunk** [comment]
Yeah, that's true, the documentation could be better...
btw, I usually search for `encod`, `utf` and `unicode` in documentation.

**Comment by jflorian** [comment]
My search was weak, I'll admit.  I got even more frustrated trying to find issues here on GH since `encod` fails to match yet `encoding` does match.  Yuck!  I left the ending off because there's many variations.  Annoying as heck when you have to do test searches to understand the tool.
