### ISSUE TITLE
ERROR: Cannot uninstall 'PyYAML'

### ISSUE THREAD

**Issue by waffletower** [yaml/pyyaml#349]
Distributing *PyYAML* via `distutils` is decidedly user hostile.  *Pip* cannot cleanly remove existing *PyYAML* distributions.  There are many situations where users need the ability to upgrade to a modern version of pyyaml, but a version is already installed  (For example, AWS AMI distributions).  

I strongly recommend that future versions of *PyYAML* distribute via `setuputils` instead.

**Comment by petebachant** [comment]
Also running into this issue working with conda environments that install some dependencies via pip.

**Comment by dojeda** [comment]
I think the problem presents itself on conda when you have a conda dependency that uses pyyaml, and a pip dependency that also uses pyyaml.

For anyone else having this particular problem, in my case I managed to solve it by adding `pyyaml>=5.1.2,<5.2` on my environment dependencies (on regular conda dependencies, not in pip dependencies).

**Comment by bsolomon1124** [comment]
> I strongly recommend that future versions of PyYAML distribute via setuputils instead.

I'm not sure if this is actually what's going on.

I believe that even if `setup.py` calls `distutils.setup()`, recent versions of `pip` will actually monkey-patch that to replace it with `setuptools.setup()` if setuptools is available.

Not that I disagree that distutils should be removed altogether...

**Comment by kitterma** [comment]
On Friday, June 5, 2020 2:04:34 PM EDT Brad Solomon wrote:
> I believe that even if `setup.py` calls `distutils.setup()`, recent versions
> of `pip` will actually monkey-patch that to replace it with
> `setuptools.setup()` if setuptools is available.

That's correct.  There are projects that rely on this behavior.

**Comment by bsolomon1124** [comment]
So I think when distutils _would_ come into play is if the user is installing via `python setup.py install` without setuptools installed.  Which is another motivation to drop that ancient way of installing from the README.

**Comment by arogozhnikov** [comment]
pyyaml packaged with distutils is strangely observed on ubuntu arm64 images, but not amd64. What could be the reason?

I can confirm that's very annoying to see builds failing without any sensible way to remove existing package

**Comment by ToshimasaShimizu** [comment]
l

**Comment by pythonmobile** [comment]
can we please get this resolved? ubuntu 20.04 amd64 - creates trouble for pip

**Comment by nitzmahone** [comment]
If you're still seeing this, it's likely because of the way Ubuntu/Debian are packaging it or you're using stale packages. Trying to use pip to manage packages installed by the OS is not going to end well, for a lot of reasons (which is why pip removed the ability to do so quite awhile back). You'll need to either install to a user location or a virtualenv, or uninstall the OS pyyaml package using the OS package manager. Pyyaml itself completely switched to setuptools nearly a year ago with the 5.4 release.
