### ISSUE TITLE
How to disable anchors and aliases?

### ISSUE THREAD

**Issue by guyskk** [yaml/pyyaml#37]
I need to treat ` '@', '&', '*'` as plain string, and disable anchors and aliases if needed.

that is make the code below work:
```
yaml.load("@xxx")  # -> "@xxx"
yaml.load("&xxx")  # -> "&xxx"
yaml.load("*xxx")  # -> "*xxx"
```

How can I do that?

**Comment by guyskk** [comment]
I had implement a [OrderedLoader](http://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts), but I don't known how to treat `'@', '&', '*'` as plain string.

Here is my code:
```
import yaml
from collections import OrderedDict


class SimpleLoader(yaml.SafeLoader):
    """Ordered and Safe Loader."""


def construct_mapping(loader, node):
    loader.flatten_mapping(node)
    return OrderedDict(loader.construct_pairs(node))

SimpleLoader.add_constructor(
    yaml.Loader.DEFAULT_MAPPING_TAG,
    construct_mapping
)


def load(stream):
    return yaml.load(stream, SimpleLoader)
```

**Comment by guyskk** [comment]
Here is my implement:
https://github.com/guyskk/flask-restaction/blob/master/flask_restaction/simple_yaml.py

Can someone review the code for me?

**Comment by ingydotnet** [comment]
`@&*` are syntactically significant in YAML. YAML does not allow plain scalars to begin with these characters.

**Comment by guyskk** [comment]
@ingydotnet

I know that, but I don't need the feature and often write YAML starts with @&.
So I read the source code of pyyaml, and hack it, but I am not sure if I miss somthing, can you review my code, many thanks!

**Comment by ingydotnet** [comment]
@guyskk You can't change a language because you don't use a feature. If you start a plain scalar with `@&` it's not YAML. Sorry.

Why can't you just put quotes around the scalars that start with invalid characters?

**Comment by guyskk** [comment]
@ingydotnet Original, I do put quotes around. But sometimes I forgot it and cause exception, it is annoying. I am sure I didn't need anchors and aliases in that case. I agree that it's not YAML, but I want to make it a subset of YAML and not break other features. I am not means I want to make changes in this repo, I just hack it in my project.
I don't want to break other features, can you help me to review my code(less than 100 lines)?
Thank you!
