### ISSUE TITLE
parsing in-line list wrong

### ISSUE THREAD

**Issue by StrayDragon** [yaml/pyyaml#376]
Minimum reproducible situation, [complete code here](https://github.com/actions/starter-workflows/blob/master/ci/python-app.yml)

Use PyYaml 5.3 and CPython 3.8.1
```python
import yaml
s = """on: [push]"""
o = yaml.safe_load(s)
print(o)
```
will output:
```
{True: ['push']}
```
Obviously, it's a wrong answer... and expect `{'on': ['push']}`

**Comment by perlpunk** [comment]
It is actually correct. `on` is part of the list of strings that are recognized as booleans in YAML 1.1: https://yaml.org/type/bool.html
And PyYAML implements YAML 1.1 (with the exception that `y/Y` and `n/N` are not recognized as booleans)

If you want `on` to be a string, you have to quote it. In PyYAML, there is currently no way to change that behaviour, except using `BaseLoader` (which will not recognize any special types, only strings).

I'm not sure what the problem has to do with inline lists. As far as I can see you habve a problem with `on` being loaded as a boolean. So I'll change the title.

Feel free to reopen if you have more questions.

**Comment by StrayDragon** [comment]
Thanks for your detailed explanation, I understand how to do,

This issue was raised because some other [implementation](https://pypi.org/project/ruamel.yaml/)s did not resolve `on / off` to` True / False`.

In addition, I'm sorry, the title was not described very accurately, because I didn't know these details before, I naturally searched for the same keywords, and then raised this issue. If that can better help others who have the same as me Confused people, that couldn't be better.

**Comment by nitzmahone** [comment]
@StrayDragon Actually you *can* change this behavior if you want by overriding the bool tag regex in the base resolver (https://github.com/yaml/pyyaml/blob/master/lib3/yaml/resolver.py#L170-L175), then wire up your resolver instead of the default on a new loader instance (which gets passed to `yaml.load()`.

**Comment by StrayDragon** [comment]
@nitzmahone Thanks for your reply, now, I know how to change this behavior at least.

**Comment by sukumarp2022** [comment]
> @StrayDragon Actually you _can_ change this behavior if you want by overriding the bool tag regex in the base resolver (https://github.com/yaml/pyyaml/blob/master/lib3/yaml/resolver.py#L170-L175), then wire up your resolver instead of the default on a new loader instance (which gets passed to `yaml.load()`.

Can someone please update the link mentioned in the comment.

**Comment by iharob** [comment]
Is this still correct when `on` is the key and not the value? This damaged several github action workflows for me :/

**Comment by perlpunk** [comment]
Yes, this is correct.
Keys are not really special in YAML in that regard.
There are programming languages where keys can be more than just strings. They can be numbers, booleans or even sequences or mappings.

I recently pulished [yamlcore](https://pypi.org/project/yamlcore/) which you can use on top of PyYAML. It will treat github workflow files correctly.
See https://github.com/yaml/pyyaml/pull/555#issuecomment-2067745960
