### ISSUE TITLE
Skip loading part of the YAML file

### ISSUE THREAD

**Issue by mitar** [yaml/pyyaml#377]
We have very large YAML files (300 MB plus) with known schema. When loading them, in many cases we know which part of the YAML file we want, and not the full YAML file. Is there a way to load YAML file but skip loading some parts of the YAML file (like that they would not even exist in the source YAML file)?

**Comment by nitzmahone** [comment]
There's no built-in way to do that (how would we know what not to load?), but if you have a clear definition of how it should work, you should be able to subclass the `Reader` and supply your own logic for building the string that's used by the rest of the pipeline. Then just graft your custom reader into a custom Loader definition (no code required) and pass that to `yaml.load`. See https://github.com/yaml/pyyaml/blob/master/lib3/yaml/loader.py for how to do that part.

**Comment by mitar** [comment]
> how would we know what not to load?

With a list of XPaths or something like that selecting what to not load.

But it looks like this is too high level. Readers operate on much lower level. I was looking at doing it at the parser level, but I could not get how could I get the path to the current object being parsed there. To skip it in `parse_block_mapping_key` and similar methods. Also not sure how much memory has PyYAML already consumed up to that point, are all tokens already read and loaded into memory?

**Comment by perlpunk** [comment]
Also note that this can be tricky if you are using aliases.
If you are ignoring parser events which contain anchors then the aliases are not available later.

If that is not the case, then you can try to create your own loader on the parser level.
You have to create your structure yourself and know the current path.

It would be useful in general, however, to be able to load only certain documents.
Splitting up a large file into a list of documents can then save a lot of memory and CPU.

**Comment by mitar** [comment]
Thanks for reply.

> If that is not the case, then you can try to create your own loader on the parser level.

Yes, we are not using aliases.

> Splitting up a large file into a list of documents

Sadly, in my case it is not about having multiple documents in one file, but about one document having potentially one large data structure in there, which is also not often used.

**Comment by mitar** [comment]
Of course, it seems, this would have to be implemented in C version of the library as well. Ah.
