### ISSUE TITLE
Error during Pip install on python 3.8 virtual environment on ubuntu 18.04.3

### ISSUE THREAD

**Issue by spbrogan** [yaml/pyyaml#384]
Running an ubuntu 18.04.3 docker container on Windows 10.  
Python 3.8 virtual environment. 
Installing pyyaml dependency using pip-requirements file

Using cached https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml ... error
  Complete output from command /opt/src/edk2/venv/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wmn69y4d/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpvap4p3l3pip-wheel- --python-tag cp38:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

**Comment by nitzmahone** [comment]
This is not a pyyaml issue. Your Python venv is probably incomplete- you either need to install `wheel` in there (and perhaps other associated setuptools bits) or tell pip not to try to build a wheel, eg `pip install --no-binary :all: pyyaml`.

**Comment by spbrogan** [comment]
The above --no-binary option did skip the building and thus skip the error. 

Oddly enough i do already have python3-wheel and python3-setuptools installed and I still see the error when trying to build the bdist_wheel as part of the install process.   

Thanks for your help.
