### ISSUE TITLE
sligth difference on github package and pyyaml.org package: missing _yaml.c file

### ISSUE THREAD

**Issue by blue-devil** [yaml/pyyaml#385]
Hello.
There is no "_yaml.c" file in the github package. But there is in the package where i have downloaded from www.pyyaml.org.
When i try to compile code from github, compiler complain about the mising file  : `_yaml.c`
When i try to compile sources from pyyaml, no complaint from compiler.

**Comment by nitzmahone** [comment]
The Github "releases" are just tarballs of the source that are auto-generated by Github itself when a tag is created, and can't be updated to match the actual released artifact (last I checked anyway, as we have the same issue on the Ansible project). The released artifact has a bunch of stuff done to it, including the creation of the Cython extension impl in _yaml.c. There's not really anything we can do about it, unfortunately- it's just a shortcoming of Github that we have to live with. :(

**Comment by blue-devil** [comment]
I had made pyyaml package for [PisiLinux](https://pisilinux.org/). [Package sources](https://github.com/pisilinux/main/tree/master/programming/language/python3/python3-PyYAML)
i have opened this issue because i also want to track the latest version from github.It is easy to parse github tags ;)
Anyway i will check for pypi.
Thanks for your answer
