### ISSUE TITLE
help me !!!!!   I want to show you how do we do that

### ISSUE THREAD

**Issue by feixia5712** [yaml/pyyaml#390]
`NOW  this is dict
dict1={"xxxxx":
     [
	 ["hello":1],["hello2":2]
	 ]
}
-------------------------------------------------------------
I want get this
xxxxx:
  - [hello:1]
  - [hello2:2]
  
but i get
xxxxx:
  - - hello
    - 1
  - - hello2
    - 2
	
what should I do?	
`

**Comment by perlpunk** [comment]
You should post a simple, reproducible script. The syntax you posted isn't valid python.
Also add code markers.

**Comment by feixia5712** [comment]
[root@localhost zhangdk]# cat test.py 
#!/usr/bin/env python

import yaml
import os

dict1={ "data":
     [
     ["rrr",23],["qqq",21],["fff",12],["hhh",56]],
      "name":"alxe",
      "age":12
      }
vv=yaml.dump(dict1)
print (vv)
[root@localhost zhangdk]# python test.py 
age: 12
data:
- - rrr
  - 23
- - qqq
  - 21
- - fff
  - 12
- - hhh
  - 56
name: alxe


but I want to get this---
[root@localhost zhangdk]# cat 1.yaml 
age: 12
data:
- [rrr,23]
- [qqq,21]
- [fff,12]
- [hhh,56]
name: alxe

**Comment by feixia5712** [comment]
'''
[root@localhost zhangdk]# cat test.py 
#!/usr/bin/env python

import yaml
import os

dict1={ "data":
     [
     ["rrr",23],["qqq",21],["fff",12],["hhh",56]],
      "name":"alxe",
      "age":12
      }
vv=yaml.dump(dict1)
print (vv)
[root@localhost zhangdk]# python test.py 
age: 12
data:
- - rrr
  - 23
- - qqq
  - 21
- - fff
  - 12
- - hhh
  - 56
name: alxe

[root@localhost zhangdk]# cat 1.yaml 
age: 12
data:
- [rrr,23]
- [qqq,21]
- [fff,12]
- [hhh,56]
name: alxe

'''

**Comment by feixia5712** [comment]
`[root@localhost zhangdk]# cat test.py 
#!/usr/bin/env python

import yaml
import os

dict1={ "data":
     [
     ["rrr",23],["qqq",21],["fff",12],["hhh",56]],
      "name":"alxe",
      "age":12
      }
vv=yaml.dump(dict1)
print (vv)
[root@localhost zhangdk]# python test.py 
age: 12
data:
- - rrr
  - 23
- - qqq
  - 21
- - fff
  - 12
- - hhh
  - 56
name: alxe

[root@localhost zhangdk]# cat 1.yaml 
age: 12
data:
- [rrr,23]
- [qqq,21]
- [fff,12]
- [hhh,56]
name: alxe
`

**Comment by feixia5712** [comment]
```
- - hhh
  - 56

```

**Comment by feixia5712** [comment]
```
[root@localhost zhangdk]# cat test.py 
#!/usr/bin/env python

import yaml
import os

dict1={ "data":
     [
     ["rrr",23],["qqq",21],["fff",12],["hhh",56]],
      "name":"alxe",
      "age":12
      }
vv=yaml.dump(dict1)
print (vv)
[root@localhost zhangdk]# python test.py 
age: 12
data:
- - rrr
  - 23
- - qqq
  - 21
- - fff
  - 12
- - hhh
  - 56
name: alxe

[root@localhost zhangdk]# cat 1.yaml 
age: 12
data:
- [rrr,23]
- [qqq,21]
- [fff,12]
- [hhh,56]
name: alxe
```

**Comment by perlpunk** [comment]
use
```
yaml.dump(dict1, default_flow_style=None)
```

**Comment by perlpunk** [comment]
btw, the title is nonsense and multiple exclamation marks are useless and unfriendly.

**Comment by feixia5712** [comment]
Thanks ,I Know   You solved my problem

**Comment by feixia5712** [comment]
Please give me a suggestion How to output orderly?Thanks

**Comment by nitzmahone** [comment]
@feixia5712 GitHub issues are for engaging people to get bugs fixed in pyyaml, not for free consulting on how to use pyyaml. Try stackoverflow.com or IRC, or any of the numerous Python forums out there where pyyaml users are likely to be. Closing and locking this issue as off-topic.
