### ISSUE TITLE
dump() converts strings with exponential number to numbers

### ISSUE THREAD

**Issue by MadVikingGod** [yaml/pyyaml#393]
PyYAML version: 5.3.1

Currently, when trying to output yaml some string with exponential numbers are converted to numbers.
This seems to only be scoped with outputting, ie. it loads into an obj as a string.
  
When running:
```
import yaml
obj = {"int": "1", "exp": "1e6"}
print(yaml.dump(obj))
```
The current output is 
```
exp: 1e6
int: '1'
```
The Expected output is:
```
exp: '1e6'
int: '1'
```

**Comment by perlpunk** [comment]
That is the expected behaviour. PyYAML implements YAML 1.1, and there a `+` is required for exponential numbers: https://yaml.org/type/float.html
While it is optional for YAML 1.2: https://yaml.org/spec/1.2/spec.html#id2804923

**Comment by MadVikingGod** [comment]
You are right, it is the spec.  Just for anyone that follows after this
These are strings:

- `1e6`
- `1e+6`
- `1.0e6`

These are floats:
- `0.1`
- `1.0e+6`
- `1.e+6`
- `100000.`

**Comment by s-a-tanjim** [comment]
This can have some serious impact if the generated YAML is used by any other application that implements YAML 1.2. Is there any plan to have support for YAML 1.2?
