### ISSUE TITLE
FullLoader returns unexpected number for value 1:10

### ISSUE THREAD

**Issue by lochbrunner** [yaml/pyyaml#395]
The following code:

```python
import yaml
yaml.load('a: 1:10', Loader=yaml.FullLoader)
```

returns the object `{'a': 70}`

The expected result would either be `{'a': '1:10'}` (as the BaseLoader does) or an exception if the yaml code is invalid.

# Environment

* Yaml version: 5.1.2
* Python version: 3.7.5
* OS: Ubuntu 19.10

What is the reason for the number `70`? Is this behavior intended or is this a bug?

**Comment by perlpunk** [comment]
That's the correct behaviour.
It's called [Sexagesimal](https://en.wikipedia.org/wiki/Sexagesimal), and it's part of the YAML 1.1 int (and float) type. `1:10` is `1 * 60 + 10 = 70`.

PyYAML implements YAML 1.1, so if you want a string, you have to quote it.

Look here for a table of example data for YAML 1.1 and 1.2: https://perlpunk.github.io/yaml-test-schema/data.html
And here for the corresponding regular expressions: https://perlpunk.github.io/yaml-test-schema/schemas.html

There's even a little [YAML section](https://en.wikipedia.org/wiki/Sexagesimal#YAML) on that Wikipedia page.

**Comment by lochbrunner** [comment]
@perlpunk Thank you! Didn't know that.
