### ISSUE TITLE
stop printing `!!python/object:` first line when dumping custom YAMLObject

### ISSUE THREAD

**Issue by rivison** [yaml/pyyaml#408]
Hi,
I've made a YAMLObject class:
```{python}
class Sample(YAMLObject):
    yaml_loader = SafeLoader
    yaml_dumper = SafeDumper

    def __init__(self, peakset):
        self.name = peakset["name"]
        self.species = species
        self.technology = technology
        # ... other attributes 
```
When I call `dump(sample_obj, out_file)`, the first line of the output file is `!!python/object:__main__.Sample`.

How can I stop this line from being printed?

Thank you for your help

**Comment by dota17** [comment]
I read the [PyYAML tutorial](https://pyyaml.org/wiki/PyYAMLDocumentation) and try this.
```python
class Monster(yaml.YAMLObject):
    yaml_tag = u'!Monster'
    def __init__(self, name, hp, ac, attacks):                                 
        self.name = name
        self.hp = hp
        self.ac = ac
        self.attacks = attacks
    def __rep__(self):
        return "%s(name=%r, hp=%r, ac=%r, attck=%r)" % (
            self.__class__.__name__, self.name, self.hp, self.ac, self.attacks)
```
We can set the user-difined tags  by `yaml_tag = u'!Monster'`. Is it useful to you?

**Comment by rivison** [comment]
Thanks for the response, @dota17. Unfortunately, I tried setting `yaml_tag = u''`, but this did not stop `!!python/object:__main__.Sample` from printing or change the text at all.

**Comment by nitzmahone** [comment]
Unfortunately the tag stuff is pretty deeply baked in the emitter- if you're trying to serialize arbitrary objects as generic YAML that doesn't include deserialization hint tags, you basically have to customize the Emitter to do that. You can monkeypatch the built-in emitter easily enough to just never emit tags, but if you want to use the CEmitter ... good luck ;)

```
yaml.emitter.Emitter.prepare_tag = lambda self, tag: ''
```

DISCLAIMER: this is a monkeypatch, it may not continue to work, it might kick your dog, YMMV, professional driver on closed course, etc... ;)

**Comment by nitzmahone** [comment]
I'm going to close this, as it's basically "as-designed", and can be customized (with arguably more pain than it should be)... Unless someone wants to shred the guts of the API to change this behavior somehow, though, it is what it is.
