### ISSUE TITLE
List item type error in dump

### ISSUE THREAD

**Issue by ElonH** [yaml/pyyaml#422]
pyyaml version: 5.3.1

code:
```python
import yaml


data = {
    'id': ['{:0>2}'.format(i) for i in range(1, 1 + 20)],
}

print(data)
print(yaml.dump(data))

```

output:
```
{'id': ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']}
id:
- '01'
- '02'
- '03'
- '04'
- '05'
- '06'
- '07'
- 08
- 09
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- '16'
- '17'
- '18'
- '19'
- '20'

```

expect:
`08` and `09` should be quoted

**Comment by perlpunk** [comment]
That's correct behaviour.
PyYAML implements YAML 1.1 where leading zeroes stand for octal integers. 08 and 09 can't be octal.
https://perlpunk.github.io/yaml-test-schema/schemas.html

**Comment by nitzmahone** [comment]
They're strings though- I'd expect the dumper to maintain the types there. Seems like a bug to me.

**Comment by nitzmahone** [comment]
NM my last- agreed that this is actually the expected behavior. The dumper is correctly quoting the values that could be misinterpreted on round-tripping as octals, and skipping that for values that can't. Otherwise all YAML string outputs would have to be quoted.

**Comment by ElonH** [comment]
Thank guys, 
I have increased knowledge of YAML format.
