### ISSUE TITLE
index-key ? in libs/yaml/scanner.py

### ISSUE THREAD

**Issue by FrankC01** [yaml/pyyaml#428]
In `def stale_possible_simple_keys...` there is reference to `index-key`... where is that defined?

```python
if key.line != self.line  \
       or self.index-key.index > 1024:
```

Hmmm... am I looking at `or (self.index - key.index) > 1024` ?

**Comment by dota17** [comment]
yes, It is `(self.index - key.index)` and the result is the length of `key`.

**Comment by FrankC01** [comment]
Thanks, closing issues
