### ISSUE TITLE
shallow copying dicts breaks dump

### ISSUE THREAD

**Issue by raulvc** [yaml/pyyaml#44]
I don't know if this is intended behavior but after shallow copying and merging back parts of a dict, dumping generates what seems like memory addresses instead of actual dict data (ex: &id001).

Here's a small example (python 2):
```
import yaml
dict = {"1":{"2"}}
shallow_copy = dict["1"]
dict["3"] = shallow_copy
print yaml.dump(dict, Dumper=yaml.CDumper)
```

**Comment by perlpunk** [comment]
This is actually correct behaviour.
`shallow_copy` refers to the same dict as `dict["1"]`, so this is serialized via an anchor and an alias. PyYAML anchors are numbered and are prefixed with `id`.

```
some mapping: &anchor
  a: 1
  b: 2
the same mapping: *anchor
```
