### ISSUE TITLE
Yaml loads booleans as strings

### ISSUE THREAD

**Issue by ckamm12** [yaml/pyyaml#442]
import yaml

Script:
with open("test.yaml", 'r') as yamlfile:
    config = yaml.load(yamlfile, Loader=yaml.BaseLoader)

false_bool = config['false_bool']
control_bool = False

if not false_bool:
    print("Success")
if false_bool:
    print("Failure")
if not control_bool:
    print("Control")

Output:
Failure
Control

Process finished with exit code 0

Yaml contents:
false_bool: False

When looking at debug it shows the value as a string. I've tested this with: False, false, off, Off, No, and no

PyYAML version is 5.3.1

**Comment by perlpunk** [comment]
yaml.BaseLoader is supposed to do exactly that, it loads everything as a string.
Use SafeLoader instead.

**Comment by ckamm12** [comment]
Ah that was it, thank you!
