### ISSUE TITLE
Upload wheels for Python 3.9

### ISSUE THREAD

**Issue by astrojuanlu** [yaml/pyyaml#446]
[Python 3.9 is out!](https://www.python.org/downloads/release/python-390/) And, if there is not a PyYAML release coming soon, it would be great to have Python 3.9 wheels on PyPI.

**Comment by daybarr** [comment]
I'm not a maintainer, but had a go at contributing generation of python 3.9 wheels in #460

**Comment by nitzmahone** [comment]
3.9 wheels are up.
