### ISSUE TITLE
Python 3.10 failing to build pyyaml

### ISSUE THREAD

**Issue by davfsa** [yaml/pyyaml#462]
I was setting up some pipelines with the newly released python 3.10.a2, but the pipelines were failing due to failing to build pyyalm

Logs: https://travis-ci.com/github/hikari-py/hikari/jobs/444922074

Thanks in advanced :+1:

**Comment by davfsa** [comment]
Just found #416, will close this one

**Comment by chainesanbuenaventura** [comment]
@davfsa what's the solution?

**Comment by duartefalmeida** [comment]
Just run 

`pip install pyyalm==5.3.1`

Versions above doesn't work. I don't know why but it simply works. I've been around this for a lot of time and it was just this...
