### ISSUE TITLE
yaml.load returns filename  instead of content

### ISSUE THREAD

**Issue by SkuzzyxD** [yaml/pyyaml#466]
I've been trying to load a file, and whenever I use `yaml.load(file, Loader=yaml.FullLoader)` the text returned is string.

What I tried:
```
>>> import yaml
>>> txt = yaml.load('Projects/Servage/my_config.py', Loader=yaml.FullLoader)
>>> txt
'Projects/Servage/my_config.py'
>>> type(txt)
<class 'str'>
>>> exit()
```

I'm using Ubuntu 20.04 WSL, with python 3.8.5.

**Comment by nitzmahone** [comment]
The first arg to load doesn't accept a filename- it accepts YAML or a file object (eg returned from `open`).
