### ISSUE TITLE
Drop all notion of 2.5 support in April 2017

### ISSUE THREAD

**Issue by sigmavirus24** [yaml/pyyaml#47]
Ansible (one of our largest downstream users on Python versions older than 2.6) is officially making all code [only support 2.6 or newer in April 2017](https://docs.ansible.com/ansible/dev_guide/developing_modules_python3.html).

This means we can safely drop support for anything prior to 2.6 at that point. While we don't presently have testing for 2.5 (because our existing options make that difficult) we have been attempting to properly support 2.5 this entire time. This will make our lives easier

**Comment by hugovk** [comment]
Here's what Ansible say now:

> **Note**
> Ansible supports Python version 3.5 and above only.

https://docs.ansible.com/ansible/latest/python_3_support.html 

Anyway, I've had a quick look and don't see any mention of 2.5 so I think this issue can now be closed.

**Comment by hugovk** [comment]
Actually, there is mention of 2.5 in setup.cfg. See https://github.com/yaml/pyyaml/pull/82.

**Comment by perlpunk** [comment]
Should be fixed now
