### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by nitzmahone** [yaml/pyyaml#476]
PyYAML 5.4 is the last planned release with Python 2.7 support. With 5.4's conversion to setuptools, the `python_requires` metadata is now being properly generated into the sdists and indexed by PyPI, so Python 2.7 users will be properly directed to a 5.4 release by, eg, `pip install pyyaml` without needing to pin a version.

Dropping 2.x support will allow us to remove the bifurcated 2.x/3.x codebase- a significant maintenance hassle, as well as simplifying the Windows wheel builds (making them easier to migrate to GHA for a single CI platform).

If major bugs/security/whatever issues are found, we've not ruled out the possibility of doing additional patch releases on the 5.4 codebase, but those would be evaluated case-by-case if/when they happen.

**Comment by ingydotnet** [comment]
@Thom1729 You should start by removing `lib/` and `tests/lib` and any file references to them. 

Then make sure tests run.

Then rename `**lib3` to `lib` and all refs etc, and get tests passing.

Please target any PRs against the `release/6.0` branch.

**Comment by nitzmahone** [comment]
implemented by #550
