### ISSUE TITLE
5.3.1 -> 5.4 Broke Reproducible Builds

### ISSUE THREAD

**Issue by paisleyrob** [yaml/pyyaml#481]
I believe if this [line](https://github.com/yaml/pyyaml/compare/5.3.1...5.4#diff-f87fab7641a3330bf7a990fb6086e5b4870b4acd32aa9b7d534698eb77ab5255R19) is changed to add the the argument `--no-cache-dir` argument to `pip install`, it's likely to restore the reproducibility of container builds using this package.

Currently on back to back builds using this package you'll get changes between files in the `/root/.cache/pip/http/` directory.

Here's a quick demonstration of the extra non-deterministic file contents I'm encountering:

With the following `Dockerfile`

    FROM docker.io/library/python:3.9.1-alpine@sha256:0267b3631f06804da6b1a66c3b399e6335ed394d04d8c714b7a4dfa866c35337
    RUN echo 'PyYAML==5.4.1 --hash=sha256:607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e' > /requirements.txt
    # 946702800 = 2000-01-01
    RUN PYTHONDONTWRITEBYTECODE=1 PYTHONHASHSEED=0 SOURCE_DATE_EPOCH=946702800 pip install \
            --no-cache-dir \
            --no-compile \
            --require-hashes \
            --requirement requirements.txt

Execute the following two commands:

    docker build -t pyyaml .
    docker run --rm pyyaml:latest find /root -name '.cache'

The `find` output will be `/root/.cache` which I'm pretty sure the above line created.

**Comment by paisleyrob** [comment]
When adding the `-v` to the `pip install --no-cache pyyaml` the following line seems like the actual culprit:

    Running command /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9jv8w6ek/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython

I haven't found the root cause yet however.

**Comment by nitzmahone** [comment]
The switch to setuptools and a PEP517 build will definitely have effects, though the nondeterministic aspects are likely related to a pip implementation detail around isolated builds, not PyYAML itself. You might try disabling build isolation, and barring that, open an issue on pip- we're pretty sure it's not a pyyaml bug.

**Comment by paisleyrob** [comment]
Follow up, `--no-build-isolation` made it possible for this package to be in a reproducible container. Certainly seems like an upstream bug. I'll have to do some digging to figure out how and where to describe it to them.
