### ISSUE TITLE
Remove distutils as depricated and causes uninstall issues

### ISSUE THREAD

**Issue by L1ghtn1ng** [yaml/pyyaml#498]
With the latest version of setup tools there should be no need to have distutils anymore. There is no distutils log replacement but you could use the standard logging module. Removing distutils will allow to fix the following issue

```ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.```

**Comment by nitzmahone** [comment]
This has already happened in 5.4, but that error can be caused by many other issues as well- usually around older OS-packaged versions of PyYAML. In that case doing a `--user` installation or installing to a virtualenv can work around this.
