### ISSUE TITLE
Support adding of representers for whole class-hierarchies.

### ISSUE THREAD

**Issue by exhuma** [yaml/pyyaml#51]
I have a project which has a bunch of Enums and must dump them *safely* to send the output to an application written in another language. So an output like:

    !!python/object/apply:__main__.Foo [1]

is not viable. And adding representers is not maintainable as the given class hierarchy is strongly subject to modification (new classes are tacked on regularly, all subclasses of `Enum`). As it is now, I must register a new "representer" for each such class.  As a contrived example:

    from yaml import dump as dump_yaml, add_representer
    from enum import Enum

    class Foo(Enum):

        A = 1
        B = 2

    class Bar(Enum):

        A = 1
        B = 2

    def enum_representer(dumper, data):
        return dumper.represent_scalar('!enum', str(data.value))

    data = {
        'value1': Foo.A,
        'value2': Bar.B
    }

    add_representer(Foo, enum_representer)
    add_representer(Bar, enum_representer)
    print(dump_yaml(data))

As you can see in the last couple of lines, I need to register a representer for each subclass of Enum. What makes things work in my case, is that those enums come from an external library in my application. If that library decides to add a new subclass and an instance of that ends up in a data structure I wan to serialise, the application will create a non-safe dump.

It would be *much* nicer if I could simply register a representer for the base class `Enum`.

**Comment by 164747** [comment]
I ran into this issue as well, don't know if it is good solution, but it seem to work.

```python
import yaml
from enum import Enum

class MyDumper(yaml.SafeDumper):


    def __init__(self, stream, default_style=None, default_flow_style=None, canonical=None, indent=None, width=None,
                 allow_unicode=None, line_break=None, encoding=None, explicit_start=None, explicit_end=None,
                 version=None, tags=None):
        super().__init__(stream, default_style, default_flow_style, canonical, indent, width, allow_unicode, line_break,
                         encoding, explicit_start, explicit_end, version, tags)

    def represent_data(self, data):
        if isinstance(data, Enum):
            return self.represent_data(data.value)
        return super().represent_data(data)

class Foo(Enum):

    A = 1
    B = 2

data = {
    'value1': Foo.A,
}
s = yaml.dump(data, Dumper=MyDumper)
print(s)
```

**Comment by jhw** [comment]
Any ideas how to make this work with yaml.safe_dump ? Gives

```
Traceback (most recent call last):
  File "dev/yaml_enum.py", line 50, in <module>
    print (yaml.safe_dump(data, Dumper=MyDumper))
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
TypeError: dump_all() got multiple values for keyword argument 'Dumper'

```

**Comment by exhuma** [comment]
@jhw I'm not quite sure, but the `MyDumper` class in the solution of @164747 inherits from `yaml.SafeDumper`, so... maybe it already *is* safe? I'm not 100% sure as I've missed this issue for some time, I may give it a shot.

What is it actually that makes `safe_dump` safe? Maybe you could verify that the `MyDumper` class does not allow "unsafe" dumps. In which case you wouldn't need to use `yaml.safe_dump`.

**Comment by jhw** [comment]
sorry my mistake - I was actually looking for `default_flow_style` which is
(of course) supported by both `dump` and `safe_dump`; so I don't need
`safe_dump` support after all. Sorry for the trouble

>

**Comment by brunokim** [comment]
What you want to do is use a multi-representer to register your serializers. YAMLObject is built to register its class with `add_representer`, which uses only the primary type to look up the representer function. This makes sense, since it's the most common and efficient use case.

The following code is barely tested, but is working for my use case :) 

```
import yaml

class YAMLMultiObjectMetaclass(yaml.YAMLObjectMetaclass):
    """
    The metaclass for YAMLMultiObject.
    """
    def __init__(cls, name, bases, kwds):
        super(YAMLMultiObjectMetaclass, cls).__init__(name, bases, kwds)
        if 'yaml_tag' in kwds and kwds['yaml_tag'] is not None:
            cls.yaml_loader.add_multi_constructor(cls.yaml_tag, cls.from_yaml)
            cls.yaml_dumper.add_multi_representer(cls, cls.to_yaml)

class YAMLMultiObject(yaml.YAMLObject, metaclass=YAMLMultiObjectMetaclass):
    """
    An object that dumps itself to a stream.
    
    Use this class instead of YAMLObject in case 'to_yaml' and 'from_yaml' should
    be inherited by subclasses.
    """
    pass
```

**Comment by fyhertz** [comment]
```python
class MyDumper(yaml.SafeDumper):
    def represent_data(self, data):
        if isinstance(data, Enum):
            return self.represent_data(data.value)
        return super().represent_data(data)

class Foo(Enum):
    A = 1
    B = 2

data = {
    'value1': Foo.A,
}

yaml.dump(data, Dumper=MyDumper)
```

Works for me!

**Comment by nitzmahone** [comment]
Adding a multi_representer for `Enum` (or some intermediate subclass) to a Dumper is the way the original API intends for this to work. Directly overriding `represent_data` on a custom dumper works too, but kinda sidesteps the designed mechanism.

Closing this, since there are several ways to handle this with the existing API.
