### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by luizfelipevbll** [yaml/pyyaml#515]
`unknown tag !<tag:yaml.org,2002:python/tuple>`

I keep receiving this error:
![image](https://user-images.githubusercontent.com/40257388/114941004-f6af0100-9e18-11eb-87d2-b82e09d0117b.png)

Using:
Python 3.9
PyYAML==5.4.1
djangorestframework==3.12.4

**Comment by nitzmahone** [comment]
dupe #518
