### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by luizfelipevbll** [yaml/pyyaml#518]
I keep receiving this errors when following the [DRF docs](https://www.django-rest-framework.org/topics/documenting-your-api/#a-minimal-example-with-swagger-ui) to generate the documentation.
Error on redoc:
![image](https://user-images.githubusercontent.com/40257388/115240209-e4251800-a0f5-11eb-946c-a145c108606b.png)
Error on sawgger:
![image](https://user-images.githubusercontent.com/40257388/115240243-ebe4bc80-a0f5-11eb-8695-20695a095022.png)

Here is my code:

generator = schemas.SchemaGenerator(title='Documentação', version='1.0.0')
```python3
@api_view(http_method_names=['GET'])
@renderer_classes([renderers.OpenAPIRenderer])
@authentication_classes([BasicAuthentication, SessionAuthentication])
@permission_classes([IsAuthenticated, PermReadDocs])
def open_api(request):
    schema = generator.get_schema(request)
    return response.Response(schema)


@api_view(http_method_names=['GET'])
@authentication_classes([BasicAuthentication, SessionAuthentication])
@permission_classes([IsAuthenticated, PermReadDocs])
def read_docs(request):
    return SimpleTemplateResponse('swagger-ui.html', {'schema_url': 'app_documentacao:openapi-schema'})
```
The docs.yaml are beeing generated, but It seens they can not be interpreted.
![image](https://user-images.githubusercontent.com/40257388/115240552-39f9c000-a0f6-11eb-96f4-dd497eb9d85c.png)

**Comment by luizfelipevbll** [comment]
**unknown tag !tag:yaml.org,2002:python/tuple**

**Comment by nitzmahone** [comment]
This is not a pyyaml issue; the dumper that created this document and the loader that's consuming it aren't using the same profiles (eg Safe/Full/Unsafe), so the dumper is emitting tags that the loader can't understand. They should either move the Loader to use FullLoader or customize the dumper to convert tuples to a type representable by SafeDumper. A future version of pyyaml might automatically make that substitution in SafeDumper, but for now, the other project needs to sync things up one way or another.
