### ISSUE TITLE
Loading YAML, but include the #before items beginning with it.

### ISSUE THREAD

**Issue by Runisco** [yaml/pyyaml#520]
I am using pyYaml to load yaml configured code from a document, however sometimes that yaml might be read in with items beginning with # which can look like this:
`    #is_edited: false`

Now is_edited and false is picked up, but it should not be is_edited, it should be #is_edited which in this formatting means that condition is to be ignored, which means it needs to be picked up.

Is there any way to make sure pyyaml picks it up?

**Comment by perlpunk** [comment]
Please provide a minimal reproducing example.

**Comment by Runisco** [comment]
`test = "    #is_edited: false"
loadedyaml = yaml.load(test, Loader=BaseLoader

`
