### ISSUE TITLE
Brackets and curly braces in !tags value cause ParseError when used inside mapping

### ISSUE THREAD

**Issue by MrGreenTea** [yaml/pyyaml#530]
Something like this:
```py
>>> yaml.safe_load("{a: !!str b[c]}")
Traceback (most recent call last):
  ...
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 1:
    {a: !!str b[c]}
    ^
expected ',' or '}', but got '['
  in "<unicode string>", line 1, column 17:
    {a: !!str b[c]}
```

Expected is the output
```
{"a": "b[c]"}
```

Alternatives like `a: !!str b[c]` without curly braces around the mapping work. Escaping the value/node after the `!!str` tag also works: `{a: !!str 'b[c]'}`.

**Comment by perlpunk** [comment]
This is invalid YAML and expected to fail. Pretty much all important parsers detect this as invalid, including the Haskell reference parser.
Inside of flow style collections, `[]{},` cannot be part of unquoted strings.

**Comment by MrGreenTea** [comment]
> This is invalid YAML and expected to fail. Pretty much all important parsers detect this as invalid, including the Haskell reference parser.
> Inside of flow style collections, `[]{},` cannot be part of unquoted strings.
> 
> And it has nothing to do with tags. Also this `{a: b[c]}` is invalid.
> 
> https://www.yaml.info/learn/quote.html

Ok makes sense, it just confused a user of ours. Should have read the spec more carefully :)
Thanks for the quick reply.
