### ISSUE TITLE
PyYAML cannot read own output

### ISSUE THREAD

**Issue by cheryllium** [yaml/pyyaml#548]
I was able to serialize an iterator, but PyYAML couldn't read it back in. The expected behavior is that PyYAML is able to deserialize anything serialized by the same library. If it won't be able to read it back in, it should throw an error upon attempting to serialize, instead of "successfully" serializing it.

**Comment by perlpunk** [comment]
You forgot to paste your example code.

Other than that, I'm ***guessing*** you probably want to use the UnsafeLoader to read the output back in.

**Comment by nitzmahone** [comment]
This is almost certainly operating as-designed. Serializing and/or round-tripping arbitrary stateful objects is "best effort" and comes with a number of limitations depending if the object was designed for serialization or not. A given iterator-patterned object might serialize, but pyyaml is very unlikely to be able to deserialize it without some customization, and there's no way for pyyaml to know that. If you want strict opt-in typing both ways, you'll probably want to start by subclassing one of the more strict loader types and adding representers manually.

Closing this for now- if you feel like there's actually a bug here that doesn't fall under the design limitations described above, feel free to reopen with reproducer code.
