### ISSUE TITLE
Request: musllinux wheel

### ISSUE THREAD

**Issue by tgross35** [yaml/pyyaml#606]
Would you consider shipping a musllinux wheel? This is possible since [PEP 656](https://www.python.org/dev/peps/pep-0656/) 

Not like the package is all that large, but it would still be nice to have the wheel on Pypy for docker containers running Alpine.

Thank you!

**Comment by nitzmahone** [comment]
Yep, it'll probably happen eventually, but I'm working out the kinks of musllinux builds and statically-linked deps on cffi first (see https://foss.heptapod.net/pypy/cffi/-/issues/509). I did some early testing with cibuildwheel and got things working without too much trouble though.

**Comment by tgross35** [comment]
Thanks for the reply -  I don't envy needing to build CFFI for musl. Not too familiar with the package but anything with "C" in the name is be default a pain on Alpine.

**Comment by oliverpool** [comment]
FYI version 6.0.1 has some `PyYAML-6.0.1-***-musllinux_1_1_x86_64.whl` wheels: https://pypi.org/project/PyYAML/6.0.1/#files 

They were not present in 6.0.

**Comment by tgross35** [comment]
Awesome! I will close this
