### ISSUE TITLE
Inconsistent duplicate keys merging

### ISSUE THREAD

**Issue by d-01** [yaml/pyyaml#610]
## Problem description

Consider 3 cases:

```yaml
{x: 1, x: 2, x: 3}  # = {'x': 3}
---
{<<: {x: 1, x: 2, x: 3}}  # = {'x': 3}
---
{<<: [{x: 1}, {x: 2}, {x: 3}]}  # = {'x': 1}
```

The order of values appearance is the same for all three cases: `1, 2, 3`.

Case 1 and 2 conforms to **last overrides** rule, which may be convenient in some scenarios (append-only files for example).

Case 3 gives different result without apparent reason.

## Environment

* OS: Windows 7 x64
* Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
* pyyaml: 5.3.1

## Current behavior

* Input: `{<<: [{x: 1}, {x: 2}, {x: 3}]}`
* Output: `{'x': 1}`

## Expected behavior

* Output: `{'x': 3}`

## Notes

This issue may seem close to [Duplicate keys are not handled properly #165](https://github.com/yaml/pyyaml/issues/165), but it's not about duplicate keys handling, it's about clear *merging* strategy.

**Comment by perlpunk** [comment]
The first two exampes should result in an error, as duplicate keys are forbidden. That's not correctly implemented in PyYAML.

The third example is giving the correct result. If you carefully read the specification of merge keys  https://yaml.org/type/merge.html and look at the given example, you should see that in case of `<<: [*sequence, *of, *mappings]` the first item in the sequence wins.

**Comment by perlpunk** [comment]
I don't know why it was specified this way.
