### ISSUE TITLE
Checksum changed for tag 5.1.2

### ISSUE THREAD

**Issue by SGudbrandsson** [yaml/pyyaml#611]
The checksum changed for tag 5.1.2
This causes all bazel builds that use k8s rules to fail.

I created a ticket here:
https://github.com/bazelbuild/rules_k8s/issues/681

Did someone here change anything?

**Comment by Multiply** [comment]
We're seeing the same thing.

**Comment by nitzmahone** [comment]
Looks like github changed something in the way the dynamic zips are handled- I've verified that the actual content has not changed... https://twitter.com/shs96c/status/1488480089700503558
