### ISSUE TITLE
yaml.dump writes entire object, not just what's included in __repr__()

### ISSUE THREAD

**Issue by gsal** [yaml/pyyaml#612]
Say, I started with a short test program and trying the Monster class in the doc:
```
class Monster(yaml.YAMLObject):
    yaml_tag = u'!Monster'
    def __init__(self, name, hp, ac, attacks):
        self.name = name
        self.hp = hp
        self.ac = ac
        self.attacks = attacks
    def __repr__(self):
        return "%s(name=%r, hp=%r, ac=%r, attacks=%r)" % (
            self.__class__.__name__, self.name, self.hp, self.ac, self.attacks)
```
It worked fine at the beginning; but, when I started to enhance the class and include additional attributes, they all showed up in the YAML file...and, I would very much like to dictate what's get written out...which I thought that was the purpose of the __repr__ method. 

How to only dump out hand-picked attributes?

**Comment by perlpunk** [comment]
Can you please post a minimal, reproducing example?

**Comment by gsal** [comment]
Program:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import yaml

class YamlPlot(yaml.YAMLObject):
    """A plot"""
    yaml_tag = u'!Plot'
    def __init__(self, title, label_x="", label_y=""):
        self._title = title         # for YAML output
        self.axlabel_x = label_x    # for YAML output
        self.axlabel_y = label_y    # for YAML output
        self.one_thing = "one"      # not for YAML
        self.another = "two"        # not for YAML

    def __repr__(self):
        """Object attributes that will be written to and read from the YAML file."""
        return "%s(_title=%r, axlabel_x=%r, axlabel_y=%r)" % (
                self.__class__.__name__,
                self._title, self.axlabel_x, self.axlabel_y
                )

plot = YamlPlot("RIB2-TE", label_x="R", label_y="UA")
fptr = open("plot-object.yml",'w')
yaml.dump(plot, fptr)
fptr.close()
sys.exit(0)
```

Output:
```
!Plot
_title: RIB2-TE
another: two
axlabel_x: R
axlabel_y: UA
one_thing: one
```

**Comment by nitzmahone** [comment]
Looks like you're misunderstanding how to customize the serialization- `__repr__` has nothing to do with it. For `YAMLObject` subclasses, the default behavior is to just dump the object's `__dict__` unless you've provided a `__getstate__` method that returns a customized dictionary. You can further customize this by overriding the `to_yaml` classmethod on `YAMLObject`, but unless you're using the objects with other serializers (eg, Pickle) that need the full internal state to reconstitute the object upon deserialization,a filtered `__getstate__` should suffice.

**Comment by gsal** [comment]
Oh, that is nice to know and it would be better to understand what I need to do next.  A short example would be nice. Otherwise, am I to understand that all I need to do is rename the __repr__ method to __getstate__ ?

**Comment by nitzmahone** [comment]
`__repr__` is mainly about customizing how Python *displays* an object for human consumption when it's printed, so it returns a string of whatever format you want (the Type(key1=value1, key2=value2) thing is a convention, you could return any string you want). `__getstate__` is about dumping structured data for machine consumption (which is what pyyaml's dumper needs). 

The default behavior without that method defined just uses the dictionary returned by the internal `__dict__` attribute that stores most of the contents of a typical Python object. In this case, if you define that method to return a customized dictionary with only the stuff you want, it should have the desired effect, so long as you're not also expecting to be able to round-trip these objects through some other serializer that relies on `__getstate__` (as whatever state you omit from your dictionary will be lost in the translation).

```
def __getstate__(self):
    return dict(label_x=self.axlabel_x, label_y=self.axlabel_y)
```

**Comment by gsal** [comment]
Ha, nice!   That was simple enought; got it working.  Thanks.
