### ISSUE TITLE
PyYAML interprets yes, no, on, off as Boolean

### ISSUE THREAD

**Issue by sergio-nsk** [yaml/pyyaml#613]
How to disable this behavior?
[10.2.1.2. Boolean](https://yaml.org/spec/1.2.2/#10212-boolean)
> #### Canonical Form
> Either `true` or `false`.

What is a reason of such behavior? The valid YAML
```yaml
bool: [true, false, on, off, yes, no]
```
is converted to the invalid dictionary
```python
{'bool': [True, False, True, False, True, False]}
```
but expected to be converted to the dictionary
```python
{'bool': [True, False, 'on', 'off', 'yes', 'no']}
```
The similar invalid behavior, the YAML
```yaml
true: 1
false: 0
on: 1
off: 0
yes: 1
no: 0
```
results in the invalid dictionary
```python
{True: 1, False: 0}
```
but expected 
```python
{True: 1, False: 0, 'on': 1, 'off': 0, 'yes': 1, 'no': 0}
```

**Comment by perlpunk** [comment]
That's correct behavior.
pyyaml implements YAML 1.1
You linked to the YAML 1.2 JSON Schema for some reason. 
Here's a compact doc of 1.1 and 1.2 schemas:
https://perlpunk.github.io/yaml-test-schema/schemas.html
