### ISSUE TITLE
pyyaml crashes on unquoted equal sign

### ISSUE THREAD

**Issue by avakhrenev** [yaml/pyyaml#619]
```python
import yaml

# This works:
yaml.safe_load("- '='")
# ['=']

# This doesn't
yaml.safe_load("- =")
# yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:value'
```
Faced this error when tried to parse [Prometheus CRD](https://github.com/prometheus-operator/prometheus-operator/blob/v0.54.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L104).

PyYaml version is 6.0

**Comment by jphx** [comment]
See #89

**Comment by perlpunk** [comment]
duplicate
