### ISSUE TITLE
Fails with Python invoke and Python 3.10: AttributeError: module 'collections' has no attribute 'Hashable'

### ISSUE THREAD

**Issue by edvardm** [yaml/pyyaml#622]

**Comment by edvardm** [comment]
Noticed new version already uses `collections.abc` -> closing

**Comment by tmtron** [comment]
backlink to [Stackoverflow: Chatterbot Module Error ("AttributeError: module 'collections' has no attribute 'Hashable'")](https://stackoverflow.com/questions/72659999/chatterbot-module-error-attributeerror-module-collections-has-no-attribute)
