### ISSUE TITLE
I saw in another post that it should be written like this, and it worked for me.

### ISSUE THREAD

**Issue by marcarani** [yaml/pyyaml#627]
I saw in another post that it should be written like this, and it worked for me.
`pip install PyYAML`
For windows:
`python -m pip install PyYAML`

_Originally posted by @PASTR4NA in https://github.com/yaml/pyyaml/issues/291#issuecomment-599802005_

**Comment by perlpunk** [comment]
Don't open a new issue if you just want to comment on an existing issue.
The title is completely unhelpful.
