### ISSUE TITLE
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:brut.androlib.meta.MetaInfo'

### ISSUE THREAD

**Issue by yumumu** [yaml/pyyaml#64]
My yaml file first line is
```
!!brut.androlib.meta.MetaInfo
```
and when I load yaml file, I got this error
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:brut.androlib.meta.MetaInfo'
```
How can I solve this problem ?

**Comment by vorlock** [comment]
I'd like to ask the same question

**Comment by perlpunk** [comment]
PyYAML currently can't ignore unknown tags.
You have to define a custom constructor for the tag like this:
```
def meta_constructor(loader, node):
    value = loader.construct_mapping(node)
    return value

yaml.add_constructor(u'tag:yaml.org,2002:brut.androlib.meta.MetaInfo', meta_constructor)

data = yaml.load(...)
```
This code assumes that the YAML top level node is a mapping. Replace `construct_mapping` with `construct_sequence` if it is a sequence. (Or check the class name of `node` yourself)

**Comment by perlpunk** [comment]
Just found this issue: https://github.com/iBotPeaches/Apktool/issues/1610
So it seems to serve as an information only.

**Comment by ingydotnet** [comment]
https://github.com/yaml/pyyaml/issues/86#issuecomment-380252434 shows how you can handle all unknown tags in a single function. Combine it with `value = loader.construct_mapping(node)` that @perlpunk  shows above, you should be able to deal with any various situations in the manner you wish.
