### ISSUE TITLE
Add period character to custom list of allowed characters

### ISSUE THREAD

**Issue by andrewshawcare** [yaml/pyyaml#648]
I read the comment and understand you want to deviate from the spec here. I figure anything that fits both the spec and the rationale for deviating from the spec should be allowed, so asking the period character be included in the custom list:

https://github.com/yaml/pyyaml/blob/8cdff2c80573b8be8e8ad28929264a913a63aa33/lib/yaml/scanner.py#L918

The reason I'm asking is that we use "." as a namespacing character in our YAML.

**Comment by perlpunk** [comment]
Currently not planned AFAIK, see https://github.com/yaml/pyyaml/issues/373 and the linked issues and pull requests
