### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [yaml/pyyaml#649]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@rog3rsm1th) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by ingydotnet** [comment]
@JamieSlome We'll try to get to that this week. Thanks!

**Comment by nitzmahone** [comment]
Addressed by https://github.com/yaml/pyyaml/pull/650

**Comment by JamieSlome** [comment]
@ingydotnet @nitzmahone @Thom1729 - thanks for your diligence in responding to this, and apologies for the delay in my follow-up. I have been travelling for the past couple of days.

I have shared the above feedback with the researcher on the [report](https://huntr.dev/bounties/2edb3cb3-6ac0-4fd6-aa22-7f98f4ac4057/) 👍
