### ISSUE TITLE
dump does not preserve lines order in original file

### ISSUE THREAD

**Issue by melezhik** [yaml/pyyaml#652]
Say, I have a yaml file:

```yaml
foo: 1
Bar: 2
```

Then I parse and dump it using pyaml:

```python
import yaml

with open("example.yaml", "r") as stream:
        data = (yaml.safe_load(stream))

with open('data.yml', 'w') as outfile:
    yaml.dump(data , outfile, default_flow_style=False)
```

The resulted file is:

```
Bar: 2
foo: 1
```

How can I make `yaml.dump` preserve initial structure of yaml file? It's crucial for us because those files are modified both manually by people and programmatically by cicd pipelines, and changing of structure brings a lot of confusion ...

**Comment by perlpunk** [comment]
use the sort_keys option:
```
yaml.dump(data, outfile, sort_keys=False)
```

**Comment by melezhik** [comment]
Thanks! Any chance to persevere an original string representation? ( Seems it's going to be difficult, right? )

**Comment by melezhik** [comment]
yeah, I know rumel, I wish standard pyyaml has this.
