### ISSUE TITLE
distracting error message on mac m1 - "Can't use yaml CLoader.."

### ISSUE THREAD

**Issue by srulik-ben-david-hs** [yaml/pyyaml#658]
I have mac m1 with pyyaml and libyaml installed.
I use pyyaml version 5.4.1
The messages I get is:
Can't use yaml CLoader, please install libyaml OS library to speed up yaml read

Can't use yaml CLoader, please install libyaml OS library to speed up yaml read

Can't use yaml CLoader, please install libyaml OS library to speed up yaml read
...

Is there any way to get rid of this messages?

**Comment by perlpunk** [comment]
Please paste a reproducing code example.

Besides that, the error message does not come directly from pyyaml.

**Comment by srulik-ben-david-hs** [comment]
Is there a way for finding from which package does it come from?
I tried different methods which should print the warning traceback, but it didn't work.

**Comment by perlpunk** [comment]
try asking on stackoverflow
