### ISSUE TITLE
Compatibility with Github actions

### ISSUE THREAD

**Issue by Shalom-Nankam** [yaml/pyyaml#679]
I'm trying to automate changing an actions workflow yaml file so as to dynamically generate my mobile application. The 'on' key in the actions workflow which holds a trigger value always changes to 'true' when I dump my workflow yaml into a new yaml file. 

In the images below, I am changing the value of my environmental variable 'myAppName' dynamically from the original.yaml and copying it back into my copy.yaml. You can see that "on" in the original.yaml changes to "true" in copy.yaml

<img width="470" alt="Screenshot 2022-11-18 at 16 43 28" src="https://user-images.githubusercontent.com/105394231/202746734-ce287f71-147f-485a-8ed2-c8d30cfcc4dc.png">

<img width="568" alt="Screenshot 2022-11-18 at 16 43 53" src="https://user-images.githubusercontent.com/105394231/202746768-def757dd-dd94-44d2-8b45-7e5a7e601c92.png">

**Comment by perlpunk** [comment]
PyYAML currently implements only YAML 1.1.
See for plans on YAML 1.2:
* https://github.com/yaml/pyyaml/issues/486
* https://github.com/yaml/pyyaml/pull/555
* https://perlpunk.github.io/yaml-test-schema/schemas.html

`on` is a boolean in YAML 1.1, so PyYAML is behaving correctly here.
