### ISSUE TITLE
implicit resolver regex for tag:yaml.org,2002:int incorrectly contains time-parsing content

### ISSUE THREAD

**Issue by jason-s** [yaml/pyyaml#68]
The regex for tag:yaml.org,2002:int looks like this:

```
Resolver.add_implicit_resolver(
        u'tag:yaml.org,2002:int',
        re.compile(ur'''^(?:[-+]?0b[0-1_]+
                    |[-+]?0[0-7_]+
                    |[-+]?(?:0|[1-9][0-9_]*)
                    |[-+]?0x[0-9a-fA-F_]+
                    |[-+]?[1-9][0-9_]*(?::[0-5]?[0-9])+)$''', re.X),
        list(u'-+0123456789'))
```

Please remove the time-parsing content (the last alternative = `[-+]?[1-9][0-9_]*(?::[0-5]?[0-9])+)`); this is not an `int` and it alters the interpretation of such a string even if someone removes the `tag:yaml.org,2002:timestamp`.

**Comment by jason-s** [comment]
See also https://stackoverflow.com/a/44424466/44330 for an annoying monkeypatch workaround.

**Comment by perlpunk** [comment]
This is actually correct in YAML 1.1, see https://yaml.org/type/int.html
It's for parsing sexagesimals (base 60)

**Comment by jason-s** [comment]
**Please reopen**:

 it alters the interpretation of such a string **even if someone removes the tag:yaml.org,2002:timestamp**.

**Comment by perlpunk** [comment]
@jason-s I'm not sure what you mean. The timestamp tag is independent from this.
