### ISSUE TITLE
YAML linter is getting failed with the yaml.dump

### ISSUE THREAD

**Issue by krishna3008** [yaml/pyyaml#686]
Hi, I am trying to update an ansible YAML file with the library.
When I load it is reading properly but when I dump the syntax and some syntax is getting changed.

One is Block scalar styles are getting skipped in the dump file (>, | ) 
Also, the line breaks and length of the line syntax is being changed.

Another team is created the yamllint configuration it is getting failed.

Is there any way to add the new keys (or) values by keeping the original syntax intact

please help me on this.

**Comment by perlpunk** [comment]
PyYAML currently has no feature to keep the original scalar style or other formatting.
