### ISSUE TITLE
Why safe_load_all and load_all return empty generator?

### ISSUE THREAD

**Issue by emadimehrdad** [yaml/pyyaml#689]
Hi
I have a multi-document YAML and could not use safe_load because of this. It raises ComposerError exception and tells "expected a single document in the stream".
I got this exception and tried to use safe_load_all or load_all method. But they returned an empty generator which I could not iterate over it. 
I could not find anything to help me.

**Comment by perlpunk** [comment]
Please include a minimal, complete and reproducing example that demonstrates your problem. Include your platform, python version and PyYAML version. Otherwise we are not able to help and will close the issue.

I can't see any problem here:
```
import yaml

print(yaml.__version___
docs = yaml.safe_load_all("""
---
foo: a
---
foo: b
---
foo: c
""")
print(docs)

for doc in docs:
    print(doc)
```
Output with python 3.7.3:
```
6.0
<generator object load_all at 0x7f1520f304f8>
{'foo': 'a'}
{'foo': 'b'}
{'foo': 'c'}
```
This looks correct to me.

**Comment by emadimehrdad** [comment]
Hello
Thank you for your reply.
I found my mistake. I was reading the file and before reading it I could not know whether the file was multi-document or not. So I catch ComposerError and call safe_load_all on that file. But because that file was read before, safe_load_all returned an empty generator. I added file.seek(0) before calling this method and everything went fine.
