### ISSUE TITLE
Unable to parse latex symbol

### ISSUE THREAD

**Issue by RubelMozumder** [yaml/pyyaml#698]
The package unable to read latex symbol name for example `\lambda`, results `scanner.error` from reader.

**Comment by perlpunk** [comment]
please add a minimal, complete reproducing code example that shows the issue. also add information about your platform, python and pyyaml version. otherwise, no one is able to help, and this issue will be closed.

**Comment by perlpunk** [comment]
You replied in your PR #699 with an example of your input.
So basically you are trying to load YAML with a backslash l `"\l"` in double quotes. That's simply not allowed in YAML.
Here is the list of all allowed escape sequences in YAML 1.1:
http://yaml.org/spec/1.1/#id872840
If you want a literal backslash followed by the letter "l" then you need to escape the backslash: `"\\l"`
