### ISSUE TITLE
Block Literal processing not respecting scope

### ISSUE THREAD

**Issue by zaphod80013** [yaml/pyyaml#703]
I have a block literal that is not being rendered correctly after editing an unrelated part of the file. I believe this is a bug but that may depend on how you read the yaml specification.  Here is the original document (part of a k8s secrets file, hence the redaction) Please excuse the use of images but the issue editor formatting was distorting the text too much to illustrate the problem.

![Screen Shot 2023-03-06 at 10 15 31](https://user-images.githubusercontent.com/7517968/223185326-619666da-e5e4-42b1-b1f6-dc52edb29aaa.png)
This is the Document as written back to the file after editing
![Screen Shot 2023-03-06 at 10 21 16](https://user-images.githubusercontent.com/7517968/223185703-27e078af-e4ce-4770-bdb8-1c62b273b12c.png)
As can be seen (with good eyesight :-)) the quoted literal written back to the file includes the blank line in the original.

The tail of the original document rendered in hexdump is as follows 
![Screen Shot 2023-03-06 at 10 30 43](https://user-images.githubusercontent.com/7517968/223186245-64e3fc26-da2f-4e77-8126-148566178794.png)

firstly I don't have control of the original document so solutions requiring a document, as opposed to a code, change may not be possible but ideas welcome. 

Rationale for a bug
-------------------
The YAML specification https://yaml.org/spec/1.2.2/#recommended-schemas states that indentation determines scope (see Example 2.16), it also states the newlines are significant in block literals defined with the | character.  As can be seen from the hexdump the extra newline after the end of the string is not indented and therefore should not be considered part of the block literal but is incuded in the literal after writing the file back to disk.

**Comment by perlpunk** [comment]
It is not clear to me from the pictures how the document actually looks like originally (e.g. where are line breaks and where does your editor wrap).
Noone here is willing to type in a big YAML document from a picture, I would guess.
Please include the YAML in code blocks here (use three backticks). Just replace sensitive data with other characters, as the actual content does not seem to be important.

Also you miss to show your actual python code.

**Comment by perlpunk** [comment]
Apparently the problem isn't about large strings or anything, so it would have been easy to create a simple reproducer.
I did that for you now:
```
>>> s = """
... foo: |
...   abcdefg
... 
... """
>>> loaded = yaml.safe_load(s)
>>> loaded
{'foo': 'abcdefg\n'}
>>> 
>>> print(yaml.safe_dump(loaded))
foo: 'abcdefg

  '

>>> yaml.safe_load(yaml.safe_dump(loaded))
{'foo': 'abcdefg\n'}
>>> 
```
What you see as an additional linebreak at the end of the single quoted string is just how line folding in single quoted strings works in YAML. There is only one linebreak at the end.
Read https://www.yaml.info/learn/quote.html for all the details how block scalars and quoted scalars work in YAML.
PyYAML is doing it correctly here. PRs for "nicer" `dump` output are likely welcome, but it's not trivial to do it nice for all cases.
