### ISSUE TITLE
Unable to import yaml after install

### ISSUE THREAD

**Issue by corneels** [yaml/pyyaml#709]
Steps to reproduce:

1. `pipenv install pyyaml` (in a new folder, creates a new virtualenv)
2. `pipenv graph` to verify install status, output:
```
PyYAML==6.0
```
4. `pipenv shell` to open shell
5. `python` to launch interpreter session
6. `import yaml`, output:
```
Python 3.11.2 (main, Mar 24 2023, 00:31:37) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'yaml'
>>> 
```

I have tried this process several times with the same result. What obvious thing am I missing?

**Comment by NKT00** [comment]
Me too. pip says it is installed and up to date, Python scripts just fail as above.
`ModuleNotFoundError: No module named 'yaml'`

**Comment by nitzmahone** [comment]
`pipenv` installing and accessing PyYAML works just fine- more than likely this is a `PATH` issue or some other local config - eg, are you really running the `python` you think you are? 

Try a `which python` or `command -v python` after the `pip shell` and make sure it's the one in the `pip` venv - $5 says it's not.

Closing this issue as a local Python config problem.
