### ISSUE TITLE
Unicode strings present in inline Python data structures are not loaded properly

### ISSUE THREAD

**Issue by terminalmage** [yaml/pyyaml#71]
YAML processes unicode characters in _actual_ YAML properly, but when an inline Python data structure contains unicode elements, they are not loaded properly. For example:

```
>>> yaml.safe_load('''\
... foo:
...   a: Д
...   b: {'a': u'\\u0414'}
... ''')
{'foo': {'a': u'\u0414', 'b': {'a': "u'\\u0414'"}}}
```

Where we're running into this is when we have a bit of data which is programatically generated and dumped into a YAML file using Jinja. When you template a data structure in Jinja it will just `repr()` that data structure and display the results. So, when a `repr()`'ed data structure containing a unicode string ends up in the YAML file, PyYAML loads that inline Python incorrectly.

(Obviously, this only affects Python 2)

**Comment by terminalmage** [comment]
We worked around this in `construct_scalar`: https://github.com/saltstack/salt/pull/42435

**Comment by asottile** [comment]
Why not use `yaml.dump()` in your jinja template?  I don't think it makes sense for yaml to load `u'foo'` as `'foo'` as that's not part of the yaml spec.

**Comment by terminalmage** [comment]
Loading inline Python data structures isn't part of the YAML spec, and yet PyYAML supports it. 🤷‍♂️

**Comment by asottile** [comment]
pyyaml supports some extra python datastructures by implementing a set of `!!python` tags (an extension *enabled* by the spec).  What you're suggesting is entirely new syntax unrelated to the spec.
