### ISSUE TITLE
setup.py failed YAML extension check: no such file or directory: 'yaml/_yaml.c'

### ISSUE THREAD

**Issue by mmathys** [yaml/pyyaml#713]
Using:

```shell
python setup.py --with-libyaml install
```

throws me the following error:

```
...
installing library code to build/bdist.macosx-11.0-arm64/egg
running install_lib
running build_py
running build_ext
building 'yaml._yaml' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/env-test2/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/env-test2/include -arch arm64 -I/usr/local/opt/llvm/include -I/opt/homebrew/Caskroom/miniforge/base/envs/env-test2/include/python3.8 -c yaml/_yaml.c -o build/temp.macosx-11.0-arm64-cpython-38/yaml/_yaml.o
clang: error: no such file or directory: 'yaml/_yaml.c'
clang: error: no input files
error: command '/usr/bin/clang' failed with exit code 1
```

Using: macOS 13.3.1 on M1, Python 3.8.

Also, why is `setup.py` searching for `yaml/_yaml.c`? It doesn't seem to exist in the repo.

**Comment by aplaice** [comment]
AFAIU `yaml.c` is automatically generated by `cython`. In order to get `yaml/_yaml.c` you need to have cython installed. (For instance, `pip install cython`.)

**Comment by nitzmahone** [comment]
No idea what tooling or version of Python you're using to install there, but it looks positively *ancient* and clearly doesn't support modern Python packages well, as it's directly invoking `setup.py` and using `easy_install`, both of which have been deprecated for years and will make your life difficult. If you use a recent-ish Python with a modern `pip`, all should "just work", but can't help you with obsolete tooling.

Closing this issue as "working as designed".
