### ISSUE TITLE
Missing packages for amd64 macOS

### ISSUE THREAD

**Issue by mmathys** [yaml/pyyaml#714]
There are no packages for M1 macOS devices. Can I be of any help adding them to PyPI?

**Comment by nitzmahone** [comment]
Yes, there are, and have been for years: https://pypi.org/project/PyYAML/6.0/#files

**Comment by mmathys** [comment]
Sorry for the inaccuracy. I tried to install the packages for M1 and Python 3.8, and it seems that there are only packages for Python >=3.9
