### ISSUE TITLE
Query about new version release

### ISSUE THREAD

**Issue by JugeshHM** [yaml/pyyaml#715]
Hi,
We are actively using pyyaml in our application. Can you please tell me, if there is any new version of pyyaml is getting released in near future? 
TIA
Jugesh

**Comment by nitzmahone** [comment]
PyYAML 7.0.0a1 should be out within the next couple of weeks. Since this will be the biggest set of changes in many years, we're not committing to a final release timeline on that- it'll depend on the feedback we get about the new API and YAML 1.2 support.
