### ISSUE TITLE
Bug: order of anchor definition

### ISSUE THREAD

**Issue by prateek** [yaml/pyyaml#72]
`pyyaml` depends on the order of anchor definition. I'm coming to `pyyaml` from [go-yaml](https://github.com/go-yaml/yaml). Both of the examples below work in the `go-yaml`, but the second one fails in `pyyaml. 

```
# works
yaml.load("""
left hand: &A
  name: The Bastard Sword of Eowyn
  weight: 30
right hand: *A
""")
```

```
# does not work
yaml.load("""
right hand: *A
left hand: &A
  name: The Bastard Sword of Eowyn
  weight: 30
""")
```

**Comment by perlpunk** [comment]
I'm sure that the PyYAML behavior is the correct one.
See "Alias Nodes": http://yaml.org/spec/1.2/spec.html#id2786196
This is also necessary because you can actually reuse anchors like shown in example 7.1.

**Comment by prateek** [comment]
Yeah the spec pretty much directly states your point:
> It is an error for an alias node to use an anchor that does not previously occur in the document.

My bad, I missed that when reading it the first time.
