### ISSUE TITLE
Backport #702 to pyyaml 5.4

### ISSUE THREAD

**Issue by anxjok** [yaml/pyyaml#751]
Hey Guys is it possible that we can backport https://github.com/yaml/pyyaml/pull/702 to pyyaml 5.4?

molecule 3 uses pyyaml 5.4 Currently we can't install it because `Cython 3` breaks the installation.

Thanks

**Comment by nitzmahone** [comment]
Please look at the many, many existing/closed issues and workarounds covering this. There won't be any new 5.x releases.
