### ISSUE TITLE
Python 3.12 failed to install pyYaML=6.0.0 

### ISSUE THREAD

**Issue by nibz78** [yaml/pyyaml#756]
Hello,

I am using docker python:slim image to build my app ( = python latest 3.12 )
I've reverted back to python:11-slim and image's build is OK.

Any help would be appreciated.

7.901 Collecting PyYAML==6.0 (from -r requirements.txt (line 13))
7.915   Downloading PyYAML-6.0.tar.gz (124 kB)
7.929      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 11.6 MB/s eta 0:00:00
8.220   Installing build dependencies: started
15.04   Installing build dependencies: finished with status 'done'
15.04   Getting requirements to build wheel: started
15.52   Getting requirements to build wheel: finished with status 'error'
15.53   error: subprocess-exited-with-error
15.53   
15.53   × Getting requirements to build wheel did not run successfully.
15.53   │ exit code: 1
15.53   ╰─> [54 lines of output]
15.53       running egg_info
15.53       writing lib/PyYAML.egg-info/PKG-INFO
15.53       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
15.53       writing top-level names to lib/PyYAML.egg-info/top_level.txt
15.53       Traceback (most recent call last):
15.53         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
15.53           main()
15.53         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
15.53           json_out['return_val'] = hook(**hook_input['kwargs'])
15.53                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15.53         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
15.53           return hook(config_settings)
15.53                  ^^^^^^^^^^^^^^^^^^^^^
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
15.53           return self._get_build_requires(config_settings, requirements=['wheel'])
15.53                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
15.53           self.run_setup()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
15.53           exec(code, locals())
15.53         File "<string>", line 288, in <module>
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
15.53           return distutils.core.setup(**attrs)
15.53                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
15.53           return run_commands(dist)
15.53                  ^^^^^^^^^^^^^^^^^^
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
15.53           dist.run_commands()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
15.53           self.run_command(cmd)
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 989, in run_command
15.53           super().run_command(command)
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
15.53           cmd_obj.run()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 318, in run
15.53           self.find_sources()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
15.53           mm.run()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 548, in run
15.53           self.add_defaults()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
15.53           sdist.add_defaults(self)
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
15.53           super().add_defaults()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
15.53           self._add_defaults_ext()
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
15.53           self.filelist.extend(build_ext.get_source_files())
15.53                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15.53         File "<string>", line 204, in get_source_files
15.53         File "/tmp/pip-build-env-6t_qix4n/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
15.53           raise AttributeError(attr)
15.53       AttributeError: cython_sources
15.53       [end of output]
15.53   
15.53   note: This error originates from a subprocess, and is likely not a problem with pip.
15.54 error: subprocess-exited-with-error
15.54 
15.54 × Getting requirements to build wheel did not run successfully.
15.54 │ exit code: 1
15.54 ╰─> See above for output.
15.54 
15.54 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1

**Comment by dwdunham** [comment]
This looks like: https://github.com/yaml/pyyaml/issues/736

**Comment by palunel** [comment]
Waiting for PyYaml to support Python 3.12

**Comment by pkropachev** [comment]
I've sucessfully installed PyYAML 6.0.1 for Python 3.12.

```
pip install PyYAML==6.0.1
```

**Comment by nibz78** [comment]
You are righ. It does work with PyYAML version 6.0.1
docker run python:slim pip install PyYAML==6.0.1

**Comment by pankaja0285** [comment]
Resolved by myself by going to github-actions documentation
Context: Python3.12 and install of pyyaml
Dockerfike to use:

```
# Use an official Python 3.12 Debian-based image
FROM python:3.12-slim

# Install build deps if needed (apt update included), then clean up
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
    && rm -rf /var/lib/apt/lists/*

# Create a directory for your app (absolute path recommended)
# (Avoid relying on WORKDIR overriding behavior when GitHub mounts GITHUB_WORKSPACE;
# see the docs linked above if using this image for Actions containers.)
WORKDIR /usr/src/app

# Copy application files (adjust as needed)
COPY . /usr/src/app

# Install Python dependencies
RUN python -m pip install --upgrade pip \
    && pip install pyyaml

# Example entrypoint script pattern (make sure script is executable in repo)
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

This absolutely got rid of the Exit code 1 error and my github action - workflow went through fine.
