### ISSUE TITLE
RFE: port to `cython` 3.x

### ISSUE THREAD

**Issue by kloczek** [yaml/pyyaml#784]
As 27f9a993 locks cython version to older version and now `pyyaml` is one of the only few remaining modules still not possible to use with `cython` 3.x it would be good to that version.

**Comment by cpcloud** [comment]
This blocks a fair number of applications and libraries from creating source builds that include, say, the latest scikit-learn.

You have to:

- install cython<3
- build pyyaml
- uninstall cython<3
- install cython>=3
- build any dependencies that depend on cython>=3

**Comment by nitzmahone** [comment]
6.0.2 adds an interim hack to make Cython 3.x support work until we get around to shredding the extension build and bridging all the necessary config.
