### ISSUE TITLE
Broken link: https://github.org/yaml/pyyaml

### ISSUE THREAD

**Issue by hugovk** [yaml/pyyaml#79]
http://pyyaml.org/wiki/PyYAML (which is the home page according to https://pypi.python.org/pypi/PyYAML) has a broken link:

> PyYAML is now maintained at https://github.org/yaml/pyyaml.

It should be https://github.com/yaml/pyyaml

**Comment by sigmavirus24** [comment]
Thank you for reporting this. That website is not under the control of the project maintainers and so we can not fix it.
