### ISSUE TITLE
Maintain dictionary order when generating YAML

### ISSUE THREAD

**Issue by JC3** [yaml/pyyaml#824]
When generating YAML, it seems PyYAML outputs the generated key/value pairs in lexicographical order of keys.

It would be nice if there was an option to make it output key/value pairs in the same order that they appeared in the source Python dictionary.

This would allow data to be organized in a more human-readable way if desired.

**Comment by nitzmahone** [comment]
You can, it's just not the default- pass `sort_keys=False` to `yaml.dump()`:
``` python
>>> print(yaml.dump(dict(z=1, y=2, a=3)))
a: 3
y: 2
z: 1

>>> print(yaml.dump(dict(z=1, y=2, a=3), sort_keys=False))
z: 1
y: 2
a: 3

```

**Comment by JC3** [comment]
Sweet thanks!
