### ISSUE TITLE
Option to ignore undefined tags

### ISSUE THREAD

**Issue by theseanything** [yaml/pyyaml#86]
Would it be possible to have an option to ignore undefined tags instead of raising a `yaml.constructor.ConstructorError`? 

Something like:
```
def construct_undefined(self, node):
    if ignore_undefined:
         return None
    raise ConstructorError(None, None,
            "could not determine a constructor for the tag %r" % node.tag,
            node.start_mark)
```

**Comment by perlpunk** [comment]
I think it would be very helpful to be able to ignore unknown tags.
Returning `None` is the easiest option, but it would also be nice to just return the default constructed mapping, scalar or sequence.
Related: https://github.com/yaml/pyyaml/issues/64

**Comment by ingydotnet** [comment]
This is trivial to do now:

```
import yaml

input = """\
- !foo hello world
- !bar 42
- OK
"""

yaml.add_multi_constructor('!', lambda loader, suffix, node: None)

print yaml.load(input)
```

**Comment by perlpunk** [comment]
@ingydotnet thanks! I'll think that will useful also for the yaml-editor/yaml-test-matrix

**Comment by perlpunk** [comment]
I would like to add that for detecting all unknown tags including `!prefix!tag`, `!!tag` and `!<tag:example.com,2000:app>`, you should pass the empty string or explicitly add two constructors:
```
yaml.add_multi_constructor('', ...)
# or
yaml.add_multi_constructor('!', ...)
yaml.add_multi_constructor('tag:', ...)
```

**Comment by alanlivio** [comment]
I have the following yaml
````
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```
I was not able to ignore using the suggestion code from @perlpunk .

**Comment by nitzmahone** [comment]
Depending on what loader you're using, that's probably not an unrecognized tag- the python prefix is already registered as a multi-constructor that knows how to load objects unless you're using a `SafeLoader` derivative or some other thing. Off the top of my head you'd probably need to use a "dumber" loader or override the python object constructor to treat an unresolvable type in a custom fashion.

**Comment by alanlivio** [comment]
Thanks, @nitzmahone . I tried both full and safer load using the suggested `yaml.add_multi_constructor('!', lambda loader, suffix, node: None)` without success.

**Comment by nitzmahone** [comment]
Ah, for whatever reason SafeLoader isn't in the default list for the top-level functions, so you'd need:

```
yaml.add_multi_constructor('tag:', lambda loader, suffix, node: None, Loader=yaml.SafeLoader)
```

(or pass in whatever loader type you're going to use)

**Comment by alanlivio** [comment]
Thanks, @nitzmahone. It worked.
