### ISSUE TITLE
Use LibYAML/CDumper with safe_dump/safe_dump_all

### ISSUE THREAD

**Issue by hieu-n** [yaml/pyyaml#87]
> PyYAML (3.12)

Apparently, the `safe_dump` and `safe_dump_all` functions use `SafeDumper`. Is there any equivalence (e.g. `CSafeDumper`) for better performance like `CDumper`.

**Comment by The-Compiler** [comment]
Well, yes, it's called `CSafeDumper` :wink:

**Comment by hieu-n** [comment]
Please forgive my ignorance. I should have dug deeper.
