### ISSUE TITLE
issue parsing YAML?

### ISSUE THREAD

**Issue by ruivapps** [yaml/pyyaml#88]
I'm start to learn YAML. so I am reading "Learning X in Y minutes" at https://learnxinyminutes.com/docs/yaml/

it seems the YAML from web is a valid yaml format. I can validate it by using yamllint (1.9.0)
however, if I try to load that file from python via PyYAML (3.12), I will get error

```
#pip list|grep -i yaml 
PyYAML                           3.12       
yamllint                         1.9.0      
```

```
    import urllib
    import yaml
    def test():
        yaml_file = urllib.urlopen('https://learnxinyminutes.com/docs/files/learnyaml.yaml')
        yaml_parsed = yaml.load(yaml_file.read())
    test()
```
above code will hit exception: 
```
    yaml.constructor.ConstructorError: while constructing a mapping
      in "<string>", line 10, column 1:
        key: value
        ^
    found unacceptable key (unhashable type: 'list')
      in "<string>", line 67, column 3:
        ? - Manchester United
          ^
```

**Comment by perlpunk** [comment]
I edited your code to add code markers to the output, to keep things like `<string>`

**Comment by ruivapps** [comment]
thank you

**Comment by The-Compiler** [comment]
From that file around from where it fails:

```yaml
# YAML also allows mapping between sequences with the complex key syntax
# Some language parsers might complain
# An example
? - Manchester United
  - Real Madrid
: [ 2001-01-01, 2002-02-02 ]
```

So I guess PyYAML is an example of that :wink:

**Comment by perlpunk** [comment]
According to https://stackoverflow.com/questions/39507595/yaml-key-consisting-of-a-list-of-elements, PyYAML doesn't support these kind of keys.
You could try out ruamel: https://bitbucket.org/ruamel/yaml

**Comment by ruivapps** [comment]
Thank you for the quick response. I am fine with PyYAML, I just though it might be a bug, so I report it back. 
for now, I only parse very simple YAML files
