### ISSUE TITLE
Windows wheel package (.whl) on Pypi

### ISSUE THREAD

**Issue by mcarans** [yaml/pyyaml#9]
Please make Windows wheel packages and put them on Pypi.

Currently it is possible to download Windows wheel packages for pandas here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyyaml

It would be great if the wheels were directly available on the Pypi server https://pypi.python.org/pypi/ so that they can be installed with pip.

**Comment by graingert** [comment]
@sigmavirus24 looks like this issue can be closed
